export declare const HEADS_DATA: readonly [{
    readonly "0": readonly [3, 3];
    readonly "10": readonly [0, 735];
    readonly "21": readonly [0, 735];
    readonly "22": readonly [0, 735];
    readonly "23": readonly [0, 735];
    readonly "26": readonly [3, 3];
    readonly "28": readonly [0, 745];
    readonly "31": readonly [0, 735];
    readonly "32": readonly [0, 735];
    readonly "33": readonly [0, 735];
    readonly "34": readonly [0, 735];
    readonly "35": readonly [0, 735];
    readonly "40": readonly [0, 745];
    readonly "41": readonly [0, 745];
    readonly "42": readonly [0, 745];
    readonly "51": readonly [0, 26];
    readonly "52": readonly [0, 26];
    readonly "53": readonly [0, 51];
    readonly "54": readonly [0, 53];
    readonly "62": readonly [3, 3];
    readonly "63": readonly [3, 3];
    readonly "64": readonly [0, 735];
    readonly "65": readonly [3, 3];
    readonly "67": readonly [0, 735];
    readonly "68": readonly [0, 735];
    readonly "73": readonly [0, 1274];
    readonly "74": readonly [0, 1274];
    readonly "75": readonly [0, 1274];
    readonly "76": readonly [0, 73];
    readonly "88": readonly [0, 745];
    readonly "95": readonly [3, 3];
    readonly "96": readonly [3, 3];
    readonly "97": readonly [3, 3];
    readonly "98": readonly [3, 3];
    readonly "102": readonly [3, 3];
    readonly "112": readonly [3, 3];
    readonly "117": readonly [0, 735];
    readonly "119": readonly [3, 3];
    readonly "120": readonly [3, 3];
    readonly "128": readonly [0, 735];
    readonly "129": readonly [3, 3];
    readonly "135": readonly [3, 3];
    readonly "136": readonly [3, 3];
    readonly "137": readonly [3, 3];
    readonly "142": readonly [0, 735];
    readonly "143": readonly [3, 3];
    readonly "144": readonly [0, 735];
    readonly "146": readonly [0, 735];
    readonly "176": readonly [0, 41];
    readonly "180": readonly [3, 3];
    readonly "181": readonly [3, 3];
    readonly "262": readonly [0, 735];
    readonly "263": readonly [0, 745];
    readonly "370": readonly [0, 735];
    readonly "377": readonly [0, 459];
    readonly "379": readonly [0, 459];
    readonly "381": readonly [0, 459];
    readonly "383": readonly [0, 460];
    readonly "399": readonly [0, 455];
    readonly "401": readonly [0, 456];
    readonly "403": readonly [0, 457];
    readonly "405": readonly [0, 458];
    readonly "408": readonly [0, 461];
    readonly "410": readonly [0, 462];
    readonly "411": readonly [0, 1274];
    readonly "413": readonly [0, 745];
    readonly "414": readonly [0, 745];
    readonly "434": readonly [0, 745];
    readonly "435": readonly [0, 745];
    readonly "436": readonly [0, 745];
    readonly "437": readonly [0, 745];
    readonly "438": readonly [0, 745];
    readonly "439": readonly [0, 745];
    readonly "440": readonly [0, 745];
    readonly "441": readonly [0, 745];
    readonly "442": readonly [0, 745];
    readonly "444": readonly [0, 745];
    readonly "445": readonly [0, 745];
    readonly "446": readonly [0, 745];
    readonly "447": readonly [0, 745];
    readonly "448": readonly [0, 745];
    readonly "449": readonly [0, 745];
    readonly "450": readonly [0, 745];
    readonly "451": readonly [0, 745];
    readonly "454": readonly [0, 745];
    readonly "455": readonly [0, 745];
    readonly "456": readonly [0, 745];
    readonly "457": readonly [0, 745];
    readonly "458": readonly [0, 745];
    readonly "459": readonly [0, 745];
    readonly "460": readonly [0, 745];
    readonly "461": readonly [0, 745];
    readonly "462": readonly [0, 745];
    readonly "464": readonly [3, 3];
    readonly "468": readonly [0, 467];
    readonly "513": readonly [0, 745];
    readonly "514": readonly [0, 745];
    readonly "515": readonly [0, 745];
    readonly "516": readonly [0, 745];
    readonly "517": readonly [0, 745];
    readonly "518": readonly [0, 745];
    readonly "519": readonly [0, 745];
    readonly "520": readonly [0, 745];
    readonly "521": readonly [0, 745];
    readonly "522": readonly [0, 745];
    readonly "543": readonly [0, 1274];
    readonly "577": readonly [0, 735];
    readonly "590": readonly [0, 698];
    readonly "591": readonly [0, 698];
    readonly "592": readonly [0, 638];
    readonly "593": readonly [0, 745];
    readonly "594": readonly [0, 745];
    readonly "595": readonly [0, 576];
    readonly "599": readonly [3, 3];
    readonly "600": readonly [3, 3];
    readonly "602": readonly [0, 769];
    readonly "604": readonly [3, 3];
    readonly "622": readonly [0, 112];
    readonly "625": readonly [3, 3];
    readonly "641": readonly [0, 835];
    readonly "652": readonly [0, 835];
    readonly "653": readonly [0, 735];
    readonly "655": readonly [3, 3];
    readonly "659": readonly [0, 467];
    readonly "677": readonly [0, 1274];
    readonly "685": readonly [0, 1274];
    readonly "692": readonly [0, 735];
    readonly "702": readonly [3, 3];
    readonly "706": readonly [3, 3];
    readonly "711": readonly [3, 3];
    readonly "712": readonly [3, 3];
    readonly "722": readonly [3, 3];
    readonly "726": readonly [0, 735];
    readonly "727": readonly [0, 735];
    readonly "728": readonly [0, 745];
    readonly "734": readonly [0, 735];
    readonly "735": readonly [3, 3];
    readonly "736": readonly [0, 735];
    readonly "737": readonly [3, 3];
    readonly "740": readonly [0, 735];
    readonly "741": readonly [0, 735];
    readonly "748": readonly [0, 735];
    readonly "753": readonly [9, 2];
    readonly "762": readonly [3, 3];
    readonly "763": readonly [3, 3];
    readonly "764": readonly [3, 3];
    readonly "773": readonly [0, 659];
    readonly "774": readonly [0, 659];
    readonly "776": readonly [0, 91];
    readonly "777": readonly [0, 91];
    readonly "778": readonly [0, 372];
    readonly "779": readonly [0, 745];
    readonly "780": readonly [0, 745];
    readonly "782": readonly [0, 793];
    readonly "783": readonly [0, 735];
    readonly "787": readonly [3, 3];
    readonly "788": readonly [3, 3];
    readonly "790": readonly [3, 3];
    readonly "791": readonly [3, 3];
    readonly "792": readonly [3, 3];
    readonly "793": readonly [3, 3];
    readonly "799": readonly [0, 745];
    readonly "800": readonly [0, 745];
    readonly "801": readonly [0, 745];
    readonly "802": readonly [0, 745];
    readonly "803": readonly [0, 745];
    readonly "804": readonly [0, 745];
    readonly "811": readonly [0, 735];
    readonly "812": readonly [0, 735];
    readonly "813": readonly [0, 735];
    readonly "814": readonly [0, 735];
    readonly "815": readonly [0, 745];
    readonly "819": readonly [0, 735];
    readonly "820": readonly [3, 3];
    readonly "826": readonly [3, 3];
    readonly "827": readonly [3, 3];
    readonly "829": readonly [0, 587];
    readonly "830": readonly [0, 587];
    readonly "831": readonly [0, 587];
    readonly "832": readonly [0, 587];
    readonly "834": readonly [0, 833];
    readonly "836": readonly [0, 835];
    readonly "837": readonly [0, 835];
    readonly "838": readonly [0, 729];
    readonly "840": readonly [0, 652];
    readonly "841": readonly [0, 1024];
    readonly "842": readonly [3, 3];
    readonly "843": readonly [3, 3];
    readonly "846": readonly [0, 847];
    readonly "848": readonly [0, 847];
    readonly "865": readonly [0, 735];
    readonly "866": readonly [0, 735];
    readonly "867": readonly [3, 3];
    readonly "868": readonly [3, 3];
    readonly "869": readonly [0, 735];
    readonly "870": readonly [0, 735];
    readonly "871": readonly [0, 745];
    readonly "872": readonly [0, 735];
    readonly "873": readonly [0, 735];
    readonly "876": readonly [3, 3];
    readonly "877": readonly [0, 847];
    readonly "880": readonly [0, 735];
    readonly "887": readonly [0, 735];
    readonly "889": readonly [3, 3];
    readonly "891": readonly [0, 847];
    readonly "893": readonly [0, 847];
    readonly "894": readonly [0, 847];
    readonly "899": readonly [0, 53];
    readonly "900": readonly [0, 53];
    readonly "901": readonly [0, 53];
    readonly "902": readonly [0, 53];
    readonly "903": readonly [3, 3];
    readonly "907": readonly [0, 784];
    readonly "908": readonly [0, 785];
    readonly "909": readonly [0, 785];
    readonly "910": readonly [0, 785];
    readonly "916": readonly [0, 735];
    readonly "917": readonly [3, 3];
    readonly "919": readonly [0, 918];
    readonly "921": readonly [0, 920];
    readonly "922": readonly [0, 920];
    readonly "924": readonly [0, 923];
    readonly "928": readonly [12, 2];
    readonly "929": readonly [3, 3];
    readonly "931": readonly [3, 3];
    readonly "942": readonly [0, 1274];
    readonly "943": readonly [3, 3];
    readonly "948": readonly [3, 3];
    readonly "950": readonly [7, 26];
    readonly "951": readonly [7, 26];
    readonly "955": readonly [3, 3];
    readonly "958": readonly [0, 956];
    readonly "959": readonly [3, 3];
    readonly "960": readonly [0, 959];
    readonly "961": readonly [3, 3];
    readonly "970": readonly [0, 845];
    readonly "973": readonly [0, 867];
    readonly "975": readonly [0, 925];
    readonly "976": readonly [0, 729];
    readonly "978": readonly [0, 977];
    readonly "979": readonly [0, 729];
    readonly "988": readonly [0, 735];
    readonly "994": readonly [0, 735];
    readonly "995": readonly [3, 3];
    readonly "999": readonly [0, 735];
    readonly "1005": readonly [0, 53];
    readonly "1006": readonly [0, 53];
    readonly "1007": readonly [3, 3];
    readonly "1009": readonly [3, 3];
    readonly "1010": readonly [3, 3];
    readonly "1012": readonly [3, 3];
    readonly "1013": readonly [3, 3];
    readonly "1014": readonly [0, 745];
    readonly "1015": readonly [0, 745];
    readonly "1016": readonly [0, 745];
    readonly "1017": readonly [0, 745];
    readonly "1018": readonly [0, 745];
    readonly "1022": readonly [3, 3];
    readonly "1023": readonly [3, 3];
    readonly "1025": readonly [0, 1024];
    readonly "1026": readonly [0, 745];
    readonly "1028": readonly [0, 638];
    readonly "1029": readonly [0, 638];
    readonly "1042": readonly [0, 587];
}, {
    readonly "1": readonly [0, 1274];
    readonly "7": readonly [3, 3];
}, {
    readonly "5": readonly [3, 3];
    readonly "6": readonly [3, 3];
    readonly "7": readonly [3, 3];
    readonly "8": readonly [3, 3];
    readonly "9": readonly [3, 3];
    readonly "28": readonly [0, 84];
    readonly "29": readonly [2, 28];
    readonly "30": readonly [2, 28];
    readonly "31": readonly [2, 28];
    readonly "32": readonly [2, 28];
    readonly "33": readonly [2, 28];
    readonly "34": readonly [0, 84];
    readonly "35": readonly [2, 28];
    readonly "37": readonly [2, 28];
    readonly "46": readonly [2, 44];
    readonly "47": readonly [2, 44];
    readonly "57": readonly [0, 1275];
    readonly "58": readonly [0, 1275];
    readonly "59": readonly [0, 1275];
    readonly "63": readonly [0, 1276];
    readonly "66": readonly [0, 769];
    readonly "67": readonly [0, 769];
    readonly "78": readonly [7, 23];
    readonly "79": readonly [7, 23];
    readonly "80": readonly [7, 23];
    readonly "81": readonly [7, 23];
    readonly "82": readonly [7, 23];
    readonly "83": readonly [7, 23];
    readonly "89": readonly [0, 937];
    readonly "90": readonly [0, 937];
    readonly "92": readonly [3, 3];
    readonly "93": readonly [3, 3];
    readonly "118": readonly [7, 23];
    readonly "119": readonly [2, 18];
    readonly "120": readonly [2, 13];
    readonly "121": readonly [2, 13];
}, {
    readonly "0": readonly [0, 26];
    readonly "1": readonly [3, 3];
    readonly "4": readonly [0, 735];
    readonly "5": readonly [3, 3];
    readonly "6": readonly [0, 735];
    readonly "7": readonly [3, 3];
    readonly "8": readonly [3, 3];
    readonly "9": readonly [3, 3];
    readonly "10": readonly [3, 3];
    readonly "11": readonly [3, 3];
    readonly "12": readonly [3, 3];
    readonly "13": readonly [3, 3];
    readonly "14": readonly [3, 3];
    readonly "15": readonly [3, 3];
    readonly "16": readonly [3, 3];
    readonly "17": readonly [3, 3];
    readonly "18": readonly [3, 3];
    readonly "19": readonly [3, 3];
    readonly "20": readonly [3, 3];
    readonly "21": readonly [3, 3];
    readonly "23": readonly [3, 3];
    readonly "24": readonly [3, 3];
    readonly "25": readonly [3, 3];
    readonly "27": readonly [3, 3];
    readonly "28": readonly [3, 3];
    readonly "29": readonly [3, 3];
    readonly "30": readonly [3, 3];
    readonly "31": readonly [3, 3];
    readonly "32": readonly [3, 3];
    readonly "33": readonly [3, 3];
    readonly "34": readonly [3, 3];
    readonly "36": readonly [3, 3];
    readonly "38": readonly [3, 3];
    readonly "39": readonly [3, 3];
    readonly "41": readonly [3, 3];
    readonly "42": readonly [3, 3];
    readonly "43": readonly [3, 3];
    readonly "44": readonly [3, 3];
    readonly "45": readonly [3, 3];
    readonly "46": readonly [3, 3];
    readonly "47": readonly [3, 3];
    readonly "49": readonly [3, 3];
    readonly "50": readonly [3, 3];
    readonly "51": readonly [3, 3];
    readonly "60": readonly [3, 3];
    readonly "61": readonly [0, 735];
    readonly "62": readonly [3, 3];
    readonly "64": readonly [3, 3];
    readonly "65": readonly [3, 3];
    readonly "66": readonly [3, 65];
    readonly "67": readonly [3, 65];
    readonly "68": readonly [3, 67];
    readonly "69": readonly [3, 3];
    readonly "71": readonly [3, 65];
    readonly "72": readonly [3, 199];
    readonly "73": readonly [0, 735];
    readonly "74": readonly [0, 735];
    readonly "75": readonly [3, 3];
    readonly "76": readonly [3, 3];
    readonly "78": readonly [3, 3];
    readonly "79": readonly [0, 735];
    readonly "80": readonly [3, 3];
    readonly "81": readonly [3, 3];
    readonly "82": readonly [3, 3];
    readonly "84": readonly [3, 3];
    readonly "85": readonly [0, 793];
    readonly "86": readonly [3, 3];
    readonly "87": readonly [3, 3];
    readonly "88": readonly [3, 65];
    readonly "89": readonly [3, 88];
    readonly "90": readonly [0, 735];
    readonly "91": readonly [0, 735];
    readonly "92": readonly [3, 3];
    readonly "93": readonly [3, 3];
    readonly "94": readonly [3, 3];
    readonly "96": readonly [3, 3];
    readonly "97": readonly [3, 3];
    readonly "98": readonly [3, 3];
    readonly "99": readonly [3, 3];
    readonly "100": readonly [3, 3];
    readonly "101": readonly [3, 3];
    readonly "102": readonly [3, 3];
    readonly "103": readonly [0, 735];
    readonly "104": readonly [3, 3];
    readonly "105": readonly [3, 3];
    readonly "106": readonly [3, 3];
    readonly "107": readonly [3, 106];
    readonly "108": readonly [3, 106];
    readonly "109": readonly [3, 3];
    readonly "110": readonly [3, 3];
    readonly "112": readonly [3, 3];
    readonly "113": readonly [3, 3];
    readonly "114": readonly [3, 3];
    readonly "115": readonly [3, 3];
    readonly "116": readonly [3, 3];
    readonly "117": readonly [3, 3];
    readonly "118": readonly [3, 3];
    readonly "119": readonly [3, 65];
    readonly "120": readonly [3, 65];
    readonly "121": readonly [3, 65];
    readonly "122": readonly [3, 3];
    readonly "123": readonly [3, 3];
    readonly "124": readonly [3, 65];
    readonly "125": readonly [3, 3];
    readonly "126": readonly [3, 3];
    readonly "127": readonly [3, 3];
    readonly "128": readonly [3, 3];
    readonly "129": readonly [3, 3];
    readonly "130": readonly [3, 3];
    readonly "131": readonly [3, 3];
    readonly "132": readonly [3, 3];
    readonly "133": readonly [3, 3];
    readonly "134": readonly [3, 3];
    readonly "135": readonly [3, 3];
    readonly "136": readonly [3, 3];
    readonly "137": readonly [3, 3];
    readonly "138": readonly [3, 3];
    readonly "139": readonly [3, 3];
    readonly "140": readonly [3, 3];
    readonly "141": readonly [3, 3];
    readonly "142": readonly [3, 3];
    readonly "143": readonly [3, 3];
    readonly "144": readonly [3, 3];
    readonly "145": readonly [3, 65];
    readonly "146": readonly [3, 3];
    readonly "147": readonly [3, 65];
    readonly "148": readonly [3, 3];
    readonly "149": readonly [3, 3];
    readonly "150": readonly [3, 147];
    readonly "151": readonly [3, 42];
    readonly "152": readonly [3, 3];
    readonly "153": readonly [3, 65];
    readonly "154": readonly [3, 3];
    readonly "155": readonly [3, 3];
    readonly "156": readonly [3, 3];
    readonly "157": readonly [3, 3];
    readonly "158": readonly [3, 157];
    readonly "159": readonly [3, 157];
    readonly "160": readonly [3, 3];
    readonly "161": readonly [3, 3];
    readonly "162": readonly [3, 3];
    readonly "163": readonly [3, 3];
    readonly "164": readonly [3, 3];
    readonly "165": readonly [3, 3];
    readonly "166": readonly [3, 3];
    readonly "167": readonly [3, 3];
    readonly "168": readonly [0, 735];
    readonly "169": readonly [0, 735];
    readonly "170": readonly [3, 3];
    readonly "171": readonly [3, 3];
    readonly "172": readonly [3, 3];
    readonly "173": readonly [0, 735];
    readonly "174": readonly [3, 3];
    readonly "176": readonly [3, 3];
}, {
    readonly "1": readonly [0, 112];
    readonly "8": readonly [4, 33];
    readonly "31": readonly [0, 735];
    readonly "32": readonly [0, 847];
    readonly "43": readonly [4, 40];
    readonly "72": readonly [4, 71];
    readonly "73": readonly [4, 71];
    readonly "74": readonly [4, 71];
    readonly "98": readonly [0, 745];
    readonly "102": readonly [4, 33];
    readonly "103": readonly [4, 173];
    readonly "104": readonly [4, 33];
    readonly "105": readonly [4, 173];
    readonly "106": readonly [4, 173];
    readonly "107": readonly [4, 33];
    readonly "108": readonly [4, 33];
    readonly "109": readonly [4, 173];
    readonly "110": readonly [4, 33];
    readonly "111": readonly [4, 33];
    readonly "112": readonly [4, 173];
    readonly "113": readonly [4, 173];
    readonly "114": readonly [4, 173];
    readonly "115": readonly [4, 173];
    readonly "116": readonly [4, 173];
    readonly "117": readonly [4, 33];
    readonly "118": readonly [4, 173];
    readonly "119": readonly [4, 33];
    readonly "120": readonly [4, 33];
    readonly "121": readonly [4, 33];
    readonly "124": readonly [0, 587];
    readonly "128": readonly [0, 847];
    readonly "130": readonly [0, 1275];
    readonly "131": readonly [0, 1275];
}, {
    readonly "3": readonly [3, 3];
    readonly "4": readonly [3, 3];
    readonly "12": readonly [3, 3];
    readonly "19": readonly [0, 53];
    readonly "20": readonly [3, 3];
    readonly "21": readonly [0, 745];
}, {}, {
    readonly "6": readonly [7, 8];
    readonly "7": readonly [7, 8];
    readonly "8": readonly [0, 84];
    readonly "9": readonly [0, 84];
    readonly "13": readonly [7, 23];
    readonly "14": readonly [7, 23];
    readonly "15": readonly [7, 23];
    readonly "34": readonly [3, 3];
    readonly "35": readonly [3, 3];
    readonly "48": readonly [0, 1276];
    readonly "49": readonly [0, 1276];
    readonly "55": readonly [0, 769];
    readonly "64": readonly [7, 46];
    readonly "66": readonly [0, 937];
    readonly "67": readonly [0, 937];
    readonly "68": readonly [7, 8];
    readonly "69": readonly [7, 8];
    readonly "72": readonly [4, 23];
}, {}, {
    readonly "1": readonly [9, 2];
}, {
    readonly "0": readonly [3, 3];
}, {}, {}, {}];
export declare type TypeHEADS = {
    "application/epub+zip": "application/zip";
    "application/vnd.amazon.mobi8-ebook": "application/x-mobipocket-ebook";
    "application/x-mobi8-ebook": "application/x-mobipocket-ebook";
    "application/mathematica": "text/plain";
    "application/x-mathematica": "text/plain";
    "application/mathml+xml": "application/xml";
    "text/mathml": "application/xml";
    "application/mbox": "text/plain";
    "application/metalink+xml": "application/xml";
    "application/metalink4+xml": "application/xml";
    "application/x-wwf": "application/pdf";
    "application/wwf": "application/pdf";
    "application/xspf+xml": "application/xml";
    "application/x-xspf+xml": "application/xml";
    "application/x-windows-themepack": "application/vnd.ms-cab-compressed";
    "application/pgp-encrypted": "text/plain";
    "application/pgp": "text/plain";
    "application/pgp-keys": "text/plain";
    "application/pgp-signature": "text/plain";
    "application/pkcs7-signature": "text/plain";
    "application/postscript": "text/plain";
    "application/raml+yaml": "application/x-yaml";
    "application/relax-ng-compact-syntax": "text/plain";
    "application/x-rnc": "text/plain";
    "application/rtf": "text/plain";
    "text/rtf": "text/plain";
    "application/sieve": "application/xml";
    "application/smil+xml": "application/xml";
    "application/smil": "application/xml";
    "application/x-apple-systemprofiler+xml": "application/xml";
    "application/x-gedcom": "text/plain";
    "text/gedcom": "text/plain";
    "video/x-javafx": "video/x-flv";
    "application/x-go-sgf": "text/plain";
    "application/x-godot-shader": "text/plain";
    "application/x-gdscript": "text/plain";
    "application/xliff+xml": "application/xml";
    "application/x-xliff": "application/xml";
    "application/toml": "text/plain";
    "application/x-yaml": "text/plain";
    "text/yaml": "text/plain";
    "text/x-yaml": "text/plain";
    "application/vnd.ms-excel.addin.macroEnabled.12": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    "application/vnd.ms-excel.sheet.binary.macroEnabled.12": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    "application/vnd.ms-excel.sheet.macroEnabled.12": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    "application/vnd.ms-excel.template.macroEnabled.12": "application/vnd.openxmlformats-officedocument.spreadsheetml.template";
    "application/vnd.ms-powerpoint.presentation.macroEnabled.12": "application/vnd.openxmlformats-officedocument.presentationml.presentation";
    "application/vnd.ms-powerpoint.slide.macroEnabled.12": "application/vnd.openxmlformats-officedocument.presentationml.slide";
    "application/vnd.ms-powerpoint.slideshow.macroEnabled.12": "application/vnd.openxmlformats-officedocument.presentationml.slideshow";
    "application/vnd.ms-powerpoint.template.macroEnabled.12": "application/vnd.openxmlformats-officedocument.presentationml.template";
    "application/vnd.ms-visio.drawing.main+xml": "application/zip";
    "application/vnd.ms-visio.template.main+xml": "application/zip";
    "application/vnd.ms-visio.stencil.main+xml": "application/zip";
    "application/vnd.ms-visio.drawing.macroEnabled.main+xml": "application/zip";
    "application/vnd.ms-visio.template.macroEnabled.main+xml": "application/zip";
    "application/vnd.ms-visio.stencil.macroEnabled.main+xml": "application/zip";
    "application/vnd.ms-word.document.macroEnabled.12": "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    "application/vnd.ms-word.template.macroEnabled.12": "application/vnd.openxmlformats-officedocument.wordprocessingml.template";
    "application/oxps": "application/zip";
    "application/vnd.ms-xpsdocument": "application/zip";
    "application/xps": "application/zip";
    "application/vnd.ms-works": "application/x-ole-storage";
    "application/vnd.visio": "application/x-ole-storage";
    "application/msword": "application/x-ole-storage";
    "application/vnd.ms-word": "application/x-ole-storage";
    "application/x-msword": "application/x-ole-storage";
    "zz-application/zz-winassoc-doc": "application/x-ole-storage";
    "application/msword-template": "application/msword";
    "application/gml+xml": "application/xml";
    "application/vnd.sun.xml.calc": "application/zip";
    "application/vnd.sun.xml.calc.template": "application/zip";
    "application/vnd.sun.xml.draw": "application/zip";
    "application/vnd.sun.xml.draw.template": "application/zip";
    "application/vnd.sun.xml.impress": "application/zip";
    "application/vnd.sun.xml.impress.template": "application/zip";
    "application/vnd.sun.xml.math": "application/zip";
    "application/vnd.sun.xml.writer": "application/zip";
    "application/vnd.sun.xml.writer.global": "application/zip";
    "application/vnd.sun.xml.writer.template": "application/zip";
    "application/vnd.oasis.opendocument.text": "application/zip";
    "application/vnd.oasis.opendocument.text-flat-xml": "application/xml";
    "application/vnd.oasis.opendocument.text-template": "application/zip";
    "application/vnd.oasis.opendocument.text-web": "application/zip";
    "application/vnd.oasis.opendocument.text-master": "application/zip";
    "application/vnd.oasis.opendocument.graphics": "application/zip";
    "application/vnd.oasis.opendocument.graphics-flat-xml": "application/xml";
    "application/vnd.oasis.opendocument.graphics-template": "application/zip";
    "application/vnd.oasis.opendocument.presentation": "application/zip";
    "application/vnd.oasis.opendocument.presentation-flat-xml": "application/xml";
    "application/vnd.oasis.opendocument.presentation-template": "application/zip";
    "application/vnd.oasis.opendocument.spreadsheet": "application/zip";
    "application/vnd.oasis.opendocument.spreadsheet-flat-xml": "application/xml";
    "application/vnd.oasis.opendocument.spreadsheet-template": "application/zip";
    "application/vnd.oasis.opendocument.chart": "application/zip";
    "application/vnd.oasis.opendocument.chart-template": "application/zip";
    "application/vnd.oasis.opendocument.formula": "application/zip";
    "application/vnd.oasis.opendocument.formula-template": "application/zip";
    "application/vnd.oasis.opendocument.database": "application/zip";
    "application/vnd.sun.xml.base": "application/zip";
    "application/vnd.oasis.opendocument.image": "application/zip";
    "application/vnd.openofficeorg.extension": "application/zip";
    "application/vnd.android.package-archive": "application/x-java-archive";
    "application/vnd.youtube.yt": "application/zip";
    "application/x-xbel": "application/xml";
    "application/x-abiword": "application/xml";
    "application/x-cue": "text/plain";
    "application/x-aportisdoc": "application/vnd.palm";
    "application/x-asp": "text/plain";
    "application/x-awk": "text/plain";
    "application/x-bzdvi": "application/x-bzip";
    "application/x-bzip-compressed-tar": "application/x-bzip";
    "application/x-bzpdf": "application/x-bzip";
    "application/x-bzpostscript": "application/x-bzip";
    "application/vnd.comicbook-rar": "application/vnd.rar";
    "application/x-cbr": "application/vnd.rar";
    "application/x-cb7": "application/x-7z-compressed";
    "application/x-cbt": "application/x-tar";
    "application/vnd.comicbook+zip": "application/zip";
    "application/x-cbz": "application/zip";
    "application/x-lrzip-compressed-tar": "application/x-lrzip";
    "application/x-raw-floppy-disk-image": "application/x-raw-disk-image";
    "application/x-fd-file": "application/x-raw-disk-image";
    "application/x-raw-disk-image-xz-compressed": "application/x-xz";
    "application/x-cd-image": "application/x-raw-disk-image";
    "application/x-iso9660-image": "application/x-raw-disk-image";
    "application/x-iso9660-appimage": "application/x-cd-image";
    "application/x-cdrdao-toc": "text/plain";
    "application/x-gd-rom-cue": "text/plain";
    "application/vnd.chess-pgn": "text/plain";
    "application/x-chess-pgn": "text/plain";
    "application/x-compressed-tar": "application/gzip";
    "application/x-cpio-compressed": "application/gzip";
    "application/x-csh": "text/plain";
    "application/ecmascript": "text/plain";
    "text/ecmascript": "text/plain";
    "application/x-designer": "application/xml";
    "text/x-kaitai-struct": "application/x-yaml";
    "text/x-qml": "text/plain";
    "application/x-desktop": "text/plain";
    "application/x-gnome-app-info": "text/plain";
    "application/x-fictionbook+xml": "application/xml";
    "application/x-fictionbook": "application/xml";
    "application/x-zip-compressed-fb2": "application/zip";
    "application/x-dia-diagram": "application/xml";
    "application/x-dia-shape": "application/xml";
    "application/x-fluid": "text/plain";
    "application/x-font-type1": "application/postscript";
    "application/x-gz-font-linux-psf": "application/gzip";
    "font/otf": "font/ttf";
    "application/x-font-otf": "font/ttf";
    "application/x-font-ttx": "application/xml";
    "application/x-gtk-builder": "application/xml";
    "application/x-glade": "application/xml";
    "application/x-gnuplot": "text/plain";
    "application/x-gzdvi": "application/gzip";
    "application/x-gzpdf": "application/gzip";
    "application/x-gzpostscript": "application/gzip";
    "application/x-java-archive": "application/zip";
    "application/x-jar": "application/zip";
    "application/java-archive": "application/zip";
    "text/x-groovy": "text/x-csrc";
    "text/x-gradle": "text/x-groovy";
    "application/x-java-jnlp-file": "application/xml";
    "application/javascript": "application/ecmascript";
    "application/x-javascript": "application/ecmascript";
    "text/javascript": "application/ecmascript";
    "application/json": "application/javascript";
    "application/jrd+json": "application/json";
    "application/json-patch+json": "application/json";
    "application/ld+json": "application/json";
    "application/schema+json": "application/json";
    "application/x-ipynb+json": "application/json";
    "application/vnd.coffeescript": "text/plain";
    "application/x-kexiproject-sqlite2": "application/x-sqlite2";
    "application/x-kexiproject-sqlite3": "application/vnd.sqlite3";
    "application/x-vnd.kde.kexi": "application/vnd.sqlite3";
    "application/x-kexiproject-sqlite": "application/vnd.sqlite3";
    "text/vnd.trolltech.linguist": "application/xml";
    "application/x-linguist": "application/xml";
    "text/vnd.qt.linguist": "application/xml";
    "application/x-lyx": "text/plain";
    "text/x-lyx": "text/plain";
    "application/x-lz4-compressed-tar": "application/x-lz4";
    "application/x-lzip-compressed-tar": "application/x-lzip";
    "application/x-lzpdf": "application/x-lzip";
    "application/x-lzma-compressed-tar": "application/x-lzma";
    "application/x-magicpoint": "text/plain";
    "video/x-matroska": "application/x-matroska";
    "video/x-matroska-3d": "application/x-matroska";
    "audio/x-matroska": "application/x-matroska";
    "application/x-mimearchive": "multipart/related";
    "text/x-ocl": "text/plain";
    "text/x-cobol": "text/plain";
    "application/x-mobipocket-ebook": "application/vnd.palm";
    "application/x-mswinurl": "text/plain";
    "application/x-m4": "text/plain";
    "application/x-nzb": "application/xml";
    "video/annodex": "application/annodex";
    "video/x-annodex": "application/annodex";
    "audio/annodex": "application/annodex";
    "audio/x-annodex": "application/annodex";
    "audio/ogg": "application/ogg";
    "audio/x-ogg": "application/ogg";
    "video/ogg": "application/ogg";
    "video/x-ogg": "application/ogg";
    "audio/x-vorbis+ogg": "audio/ogg";
    "audio/vorbis": "audio/ogg";
    "audio/x-vorbis": "audio/ogg";
    "audio/x-flac+ogg": "audio/ogg";
    "audio/x-oggflac": "audio/ogg";
    "audio/x-opus+ogg": "audio/ogg";
    "audio/x-speex+ogg": "audio/ogg";
    "video/x-theora+ogg": "video/ogg";
    "video/x-theora": "video/ogg";
    "video/x-ogm+ogg": "video/ogg";
    "video/x-ogm": "video/ogg";
    "application/vnd.ms-publisher": "application/x-ole-storage";
    "application/x-msi": "application/x-ole-storage";
    "application/x-perl": "text/plain";
    "text/x-perl": "text/plain";
    "application/x-php": "text/plain";
    "application/x-qtiplot": "text/plain";
    "application/x-quicktime-media-link": "video/quicktime";
    "application/x-quicktimeplayer": "video/quicktime";
    "text/x-reject": "text/plain";
    "application/x-reject": "text/plain";
    "application/x-source-rpm": "application/x-rpm";
    "application/x-ruby": "text/plain";
    "application/x-markaby": "application/x-ruby";
    "text/x-crystal": "text/plain";
    "text/crystal": "text/plain";
    "text/rust": "text/plain";
    "application/x-shared-library-la": "text/plain";
    "application/x-shellscript": "text/plain";
    "text/x-sh": "text/plain";
    "application/x-subrip": "text/plain";
    "application/x-srt": "text/plain";
    "text/vtt": "text/plain";
    "application/x-sami": "text/plain";
    "text/x-microdvd": "text/plain";
    "text/x-mpl2": "text/plain";
    "text/x-mpsub": "text/plain";
    "text/x-ssa": "text/plain";
    "text/x-subviewer": "text/plain";
    "text/x-iMelody": "text/plain";
    "audio/x-iMelody": "text/plain";
    "audio/iMelody": "text/plain";
    "text/x-mrml": "application/xml";
    "application/x-tarz": "application/x-compress";
    "application/x-theme": "application/x-desktop";
    "text/troff": "text/plain";
    "application/x-troff": "text/plain";
    "text/x-troff": "text/plain";
    "application/x-troff-man": "text/plain";
    "application/x-tzo": "application/x-lzop";
    "application/x-xz-compressed-tar": "application/x-xz";
    "application/x-zstd-compressed-tar": "application/zstd";
    "application/x-xzpdf": "application/x-xz";
    "application/x-wais-source": "text/plain";
    "application/xhtml+xml": "application/xml";
    "audio/vnd.dts.hd": "audio/vnd.dts";
    "audio/x-dtshd": "audio/vnd.dts";
    "audio/x-aifc": "application/x-iff";
    "audio/x-aiffc": "application/x-iff";
    "audio/x-aiff": "application/x-iff";
    "audio/x-m4r": "video/mp4";
    "audio/x-m4b": "audio/mp4";
    "video/3gpp": "video/mp4";
    "video/3gp": "video/mp4";
    "audio/3gpp": "video/mp4";
    "video/3gpp-encrypted": "video/mp4";
    "audio/3gpp-encrypted": "video/mp4";
    "audio/x-rn-3gpp-amr": "video/mp4";
    "audio/x-rn-3gpp-amr-encrypted": "video/mp4";
    "audio/x-rn-3gpp-amr-wb": "video/mp4";
    "audio/x-rn-3gpp-amr-wb-encrypted": "video/mp4";
    "audio/x-mpegurl": "text/plain";
    "audio/mpegurl": "text/plain";
    "application/m3u": "text/plain";
    "audio/x-mp3-playlist": "text/plain";
    "audio/m3u": "text/plain";
    "audio/x-m3u": "text/plain";
    "application/vnd.apple.mpegurl": "text/plain";
    "audio/x-minipsf": "audio/x-psf";
    "audio/x-psflib": "audio/x-psf";
    "audio/x-ms-wma": "application/vnd.ms-asf";
    "audio/wma": "application/vnd.ms-asf";
    "text/vnd.rn-realtext": "text/plain";
    "video/x-mjpeg": "image/jpeg";
    "image/openraster": "application/zip";
    "application/x-ufraw": "application/xml";
    "image/x-adobe-dng": "image/tiff";
    "image/x-canon-crw": "image/x-dcraw";
    "image/x-canon-cr2": "image/tiff";
    "image/x-canon-cr3": "image/x-dcraw";
    "image/x-fuji-raf": "image/x-dcraw";
    "image/x-kodak-dcr": "image/tiff";
    "image/x-kodak-k25": "image/tiff";
    "image/x-kodak-kdc": "image/tiff";
    "image/x-minolta-mrw": "image/x-dcraw";
    "image/x-nikon-nef": "image/tiff";
    "image/x-nikon-nrw": "image/tiff";
    "image/x-olympus-orf": "image/x-dcraw";
    "image/x-panasonic-rw": "image/x-dcraw";
    "image/x-panasonic-raw": "image/x-dcraw";
    "image/x-panasonic-rw2": "image/x-dcraw";
    "image/x-panasonic-raw2": "image/x-dcraw";
    "image/x-pentax-pef": "image/tiff";
    "image/x-sigma-x3f": "image/x-dcraw";
    "image/x-sony-srf": "image/tiff";
    "image/x-sony-sr2": "image/tiff";
    "image/x-sony-arw": "image/tiff";
    "image/svg+xml": "application/xml";
    "image/svg+xml-compressed": "application/gzip";
    "image/x-bzeps": "application/x-bzip";
    "application/x-docbook+xml": "application/xml";
    "application/docbook+xml": "application/xml";
    "application/vnd.oasis.docbook+xml": "application/xml";
    "image/vnd.djvu+multipage": "image/vnd.djvu";
    "image/x-eps": "application/postscript";
    "image/x-gzeps": "application/gzip";
    "image/x-ilbm": "application/x-iff";
    "image/x-iff": "application/x-iff";
    "image/x-portable-bitmap": "image/x-portable-anymap";
    "image/x-portable-graymap": "image/x-portable-anymap";
    "image/x-portable-pixmap": "image/x-portable-anymap";
    "message/rfc822": "text/plain";
    "model/iges": "text/plain";
    "model/gltf+json": "application/json";
    "model/vrml": "text/plain";
    "model/obj": "text/plain";
    "model/mtl": "text/plain";
    "text/calendar": "text/plain";
    "text/x-vcalendar": "text/plain";
    "application/ics": "text/plain";
    "text/css": "text/plain";
    "text/vcard": "text/plain";
    "text/directory": "text/plain";
    "text/x-vcard": "text/plain";
    "text/turtle": "text/plain";
    "text/x-txt2tags": "text/plain";
    "text/x-verilog": "text/plain";
    "text/x-svhdr": "text/x-verilog";
    "text/x-svsrc": "text/x-verilog";
    "text/x-vhdl": "text/plain";
    "application/rdf+xml": "application/xml";
    "text/rdf": "application/xml";
    "text/x-rst": "text/plain";
    "application/owl+xml": "application/xml";
    "text/richtext": "text/plain";
    "application/rss+xml": "application/xml";
    "text/rss": "application/xml";
    "application/atom+xml": "application/xml";
    "text/x-opml+xml": "application/xml";
    "text/x-opml": "application/xml";
    "text/sgml": "text/plain";
    "text/spreadsheet": "text/plain";
    "text/tab-separated-values": "text/plain";
    "text/vnd.graphviz": "text/plain";
    "text/vnd.sun.j2me.app-descriptor": "text/plain";
    "text/vnd.wap.wml": "application/xml";
    "text/vnd.wap.wmlscript": "text/plain";
    "text/vnd.senx.warpscript": "text/plain";
    "text/x-adasrc": "text/plain";
    "text/x-bibtex": "text/plain";
    "text/x-c++hdr": "text/x-chdr";
    "text/x-c++src": "text/x-csrc";
    "text/x-chdr": "text/x-csrc";
    "text/x-cmake": "text/plain";
    "text/x-common-lisp": "text/plain";
    "text/csv": "text/plain";
    "text/x-comma-separated-values": "text/plain";
    "text/x-csv": "text/plain";
    "text/csv-schema": "text/plain";
    "text/x-csrc": "text/plain";
    "text/x-c": "text/plain";
    "text/x-csharp": "text/x-csrc";
    "text/x-vala": "text/x-csrc";
    "text/x-ooc": "text/x-csrc";
    "text/x-dcl": "text/plain";
    "text/x-dsl": "text/plain";
    "text/x-dsrc": "text/x-csrc";
    "application/xml-dtd": "text/plain";
    "text/x-dtd": "text/plain";
    "text/x-eiffel": "text/plain";
    "text/x-emacs-lisp": "text/plain";
    "text/x-elixir": "text/plain";
    "text/x-erlang": "text/plain";
    "text/x-fortran": "text/plain";
    "text/x-genie": "text/plain";
    "text/x-gettext-translation": "text/plain";
    "text/x-po": "text/plain";
    "application/x-gettext": "text/plain";
    "text/x-gettext-translation-template": "text/plain";
    "text/x-pot": "text/plain";
    "text/x-gherkin": "text/plain";
    "text/html": "text/plain";
    "text/cache-manifest": "text/plain";
    "text/x-google-video-pointer": "text/plain";
    "text/google-video-pointer": "text/plain";
    "text/x-haskell": "text/plain";
    "text/x-idl": "text/plain";
    "text/x-java": "text/x-csrc";
    "text/x-ldif": "text/plain";
    "text/x-lilypond": "text/plain";
    "text/x-literate-haskell": "text/plain";
    "text/x-log": "text/plain";
    "text/x-makefile": "text/plain";
    "text/markdown": "text/plain";
    "text/x-markdown": "text/plain";
    "text/x-moc": "text/plain";
    "text/x-ms-regedit": "text/plain";
    "text/x-mof": "text/x-csrc";
    "text/x-mup": "text/plain";
    "text/x-objcsrc": "text/x-csrc";
    "text/x-objc++src": "text/x-objcsrc";
    "text/x-ocaml": "text/plain";
    "text/x-opencl-src": "text/x-csrc";
    "text/x-matlab": "text/plain";
    "text/x-octave": "text/plain";
    "text/x-modelica": "text/plain";
    "text/x-pascal": "text/plain";
    "text/x-patch": "text/plain";
    "text/x-diff": "text/plain";
    "text/x-dart": "text/plain";
    "text/x-go": "text/plain";
    "text/x-python3": "text/x-python";
    "text/x-python": "text/plain";
    "text/x-sagemath": "text/x-python";
    "text/x-lua": "text/plain";
    "text/x-nfo": "text/x-readme";
    "text/x-rpm-spec": "text/plain";
    "text/x-sass": "text/plain";
    "text/x-scala": "text/plain";
    "text/x-scheme": "text/plain";
    "text/x-scss": "text/plain";
    "text/x-setext": "text/plain";
    "application/sql": "text/plain";
    "text/x-sql": "text/plain";
    "text/tcl": "text/plain";
    "text/x-tcl": "text/plain";
    "text/x-tex": "text/plain";
    "application/x-tex": "text/plain";
    "text/x-texinfo": "text/plain";
    "text/x-troff-me": "text/plain";
    "text/x-troff-mm": "text/troff";
    "text/x-troff-ms": "text/plain";
    "text/x-twig": "text/plain";
    "text/x-uil": "text/plain";
    "text/x-uuencode": "text/plain";
    "zz-application/zz-winassoc-uu": "text/plain";
    "text/vbscript": "text/plain";
    "text/vbs": "text/plain";
    "text/x-xmi": "application/xml";
    "text/x-xslfo": "application/xml";
    "text/x-iptables": "text/plain";
    "text/x-dbus-service": "text/plain";
    "text/x-systemd-unit": "text/plain";
    "application/xslt+xml": "application/xml";
    "application/xml": "text/plain";
    "text/xml": "text/plain";
    "application/xml-external-parsed-entity": "application/xml";
    "text/xml-external-parsed-entity": "application/xml";
    "video/vnd.mpegurl": "text/plain";
    "video/x-mpegurl": "text/plain";
    "application/x-netshow-channel": "application/vnd.ms-asf";
    "video/x-ms-wmv": "application/vnd.ms-asf";
    "application/sdp": "text/plain";
    "application/x-sdp": "text/plain";
    "application/vnd.sdp": "text/plain";
    "application/vnd.google-earth.kml+xml": "application/xml";
    "application/vnd.google-earth.kmz": "application/zip";
    "application/geo+json": "application/json";
    "application/vnd.geo+json": "application/json";
    "application/gpx+xml": "application/xml";
    "application/gpx": "application/xml";
    "application/x-gpx+xml": "application/xml";
    "application/x-gpx": "application/xml";
    "application/x-ica": "text/plain";
    "application/vnd.mozilla.xul+xml": "application/xml";
    "application/x-xpinstall": "application/zip";
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "application/zip";
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template": "application/zip";
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "application/zip";
    "application/vnd.openxmlformats-officedocument.presentationml.slide": "application/zip";
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow": "application/zip";
    "application/vnd.openxmlformats-officedocument.presentationml.template": "application/zip";
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "application/zip";
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template": "application/zip";
    "application/x-cisco-vpn-settings": "text/plain";
    "application/x-it87": "text/plain";
    "application/x-ccmx": "text/plain";
    "application/trig": "text/plain";
    "application/x-trig": "text/plain";
    "application/vnd.apple.keynote": "application/zip";
    "application/x-iwork-keynote-sffkey": "application/zip";
    "application/vnd.apple.numbers": "application/zip";
    "application/x-iwork-numbers-sffnumbers": "application/zip";
    "application/vnd.apple.pages": "application/zip";
    "application/x-iwork-pages-sffpages": "application/zip";
    "application/vnd.apple.pkpass": "application/zip";
    "application/x-pagemaker": "application/x-ole-storage";
    "application/vnd.flatpak.repo": "text/plain";
    "application/vnd.flatpak.ref": "text/plain";
    "application/vnd.appimage": "application/vnd.squashfs";
    "application/vnd.snap": "application/vnd.squashfs";
    "model/3mf": "application/zip";
    "application/vnd.ms-3mfdocument": "application/zip";
    "text/x.gcode": "text/plain";
    "application/ovf": "application/x-tar";
    "application/x-virtualbox-ova": "application/x-tar";
    "application/x-pyspread-bz-spreadsheet": "application/x-bzip";
    "text/x-kotlin": "text/plain";
    "text/org": "text/plain";
    "application/sparql-results+xml": "application/xml";
};
