/* eslint-disable max-len */

export const NOTES_LIST = ["Manual page","Lotus 1-2-3 spreadsheet","T602 document","Amiga SoundTracker audio","ATK inset","Applix Words document","Atom syndication feed","DocBook document","ECMAScript program","electronic book document","GML document","GPX geographic data","Java archive","Java class","JavaScript program","JSON document","JSON schema","Mathematica Notebook file","MathML document","mailbox file","Metalink file","Word document","Word template","Graphviz DOT graph","MXF video","shared library","XAR archive","ODA document","Ogg multimedia file","OpenXPS document","PDF document","PGP/MIME-encrypted message header","detached OpenPGP signature","PGP keys","plain text document","PKCS#10 certification request","PKCS#7 file","detached S/MIME signature","PKCS#8 private key","X.509 certificate","certificate revocation list","PkiPath certification path","MP3 ShoutCast playlist","PostScript document","Adobe Illustrator document","EPS image","RDF file","RELAX NG XML schema","Rust source code","GIMP brush","RSS summary","RTF document","SDP multicast stream file","StarImpress presentation","SMIL document","SAMI subtitles","SPARQL query","SPARQL query results","Android package","Media playlist","Dart source code","Adobe FrameMaker document","KML geographic data","KML geographic compressed data","HPGL file","PCL file","Scala source code","ICC profile","RealMedia document","Karbon14 drawing","KChart chart","KFormula formula","Kivio flowchart","Kontour drawing","KPresenter presentation","KSpread spreadsheet","KWord document","Org-mode file","Scheme source code","Lotus Word Pro document","Adobe FrameMaker MIF document","Musepack audio","XUL interface document","Microsoft Cabinet archive","Excel spreadsheet","Excel add-in","Excel 2007 binary spreadsheet","Excel spreadsheet template","CHM document","STL 3D model","PowerPoint presentation","translation template","PowerPoint add-in","PowerPoint slide","PowerPoint presentation template","Word document template","Microsoft Works document","WPL playlist","XPS document","ODC chart","ODC template","ODB database","ODF formula","ODF template","ODG drawing","ODG template","ODI image","ODP presentation","ODP template","ODS spreadsheet","ODS template","ODT document","ODM document","ODT template","OTH template","OpenOffice.org extension","PowerPoint 2007 presentation","PowerPoint 2007 slide","PowerPoint 2007 show","PowerPoint 2007 presentation template","Excel 2007 spreadsheet","Excel 2007 spreadsheet template","Word 2007 document","Word 2007 document template","MagicPoint presentation","Palm OS database","AportisDoc document","RealAudio document","SMAF audio","StarCalc spreadsheet","StarDraw drawing","StarMath formula","StarWriter document","OpenOffice Calc spreadsheet","OpenOffice Calc template","OpenOffice Draw drawing","OpenOffice Draw template","OpenOffice Impress presentation","OpenOffice Impress template","OpenOffice Math formula","OpenOffice Writer document","OpenOffice Writer global document","OpenOffice Writer template","SIS package","SISX package","MPEG-2 transport stream","network packet capture","Microsoft Visio document","TGA image","WordPerfect document","WinHelp help file","7-zip archive","AbiWord document","ACE archive","Apple disk image","BCPIO archive","BitTorrent seed file","Bzip archive","comic book archive (rar container)","comic book archive (tar container)","comic book archive (zip container)","comic book archive (7z container)","PGN chess game notation","Windows Media Station file","CPIO archive","C shell script","Debian package","Kodak DCR raw image","WiiWare bundle","Doom WAD file","Godot Engine resource","TeX DVI document","BDF font","PostScript type-1 font","Linux PSF console font","PSF audio","PCF font","Cisco VPN settings","Adobe font metrics","Shockwave Flash file","Gnumeric spreadsheet","Tar archive","HDF document","raw CD image","Sega CD disc image","Sega Pico ROM","Sega Saturn disc image","Dreamcast disc image","Wii disc image","GameCube disc image","JNLP file","TeX document","LHA archive","Mobipocket e-book","WMF image","JET database","DOS/Windows executable","Windows Installer package","EMF image","Microsoft Publisher document","WRI document","Unidata NetCDF document","NewzBin usenet index","PKCS#12 certificate bundle","PKCS#7 certificate bundle","RAR archive","shell script","shell archive","SQL code","StuffIt archive","SubRip subtitles","SV4 CPIO archive","SV4 CPIO archive (with CRC)","Tcl script","TeXInfo document","TGIF document","OBJ 3D model","Ustar archive","WAIS source code","DER/PEM/Netscape-encoded X.509 certificate","XFig image","XLIFF translation file","XPInstall installer module","XZ archive","XHTML page","XML document","XSLT stylesheet","DTD file","XSPF playlist","Zip archive","ULAW (Sun) audio","MIDI audio","MPEG-4 audio","MP3 audio","MP2 audio","MPEG video","Ogg audio","Ogg Vorbis audio","Ogg FLAC audio","Ogg Speex audio","Ogg Theora video","Ogg video","Apple System Profiler","Speex audio","Opus audio","Scream Tracker 3 audio","DTS audio","DTS-HD audio","AAC audio","AIFF/Amiga/Mac audio","AIFC audio","FLAC audio","Matroska audio","Microsoft ASX playlist","Windows Media audio","RealMedia playlist","WAV audio","FastTracker II audio","Font collection","OpenType font","TrueType font","WOFF font","WOFF2 font","Windows BMP image","CGM image","CCITT G3 fax image","GIF image","IEF image","JPEG image","Khronos texture image","PNG image","SGI image","SVG image","compressed SVG image","TIFF image","Photoshop image","DjVu image","DjVu document","MicroDVD subtitles","MPSub subtitles","SubViewer subtitles","AutoCAD image","DXF vector image","MDI image","WBMP image","WebP image","3D Studio image","Nintendo 3DS ROM","CMU raster image","Windows icon","Commodore 64 audio","PCX image","Macintosh Quickdraw/PICT drawing","PNM image","PBM image","PGM image","PPM image","RGB image","XBM image","XPM image","X window image","email message","IGES document","VRML document","Web application cache file","VCS/ICS calendar","CSS stylesheet","CSV document","HTML document","application log","rich text document","SGML document","TSV document","Troff document","Perl script","Troff ME input document","Troff MS input document","Turtle document","electronic business card","JAD document","WML document","WMLScript program","C source code","C++ source code","C header","C++ header","Fortran source code","Java source code","NFO document","OPML syndication feed","Pascal source code","Setext document","uuencoded file","3GPP multimedia file","3GPP2 multimedia file","JPEG-2000 JPM image","JPEG-2000 MJ2 video","MPEG-4 video","QuickTime video","Video playlist","Vivo video","WebM video","FLIC animation","Flash video","Matroska video","Matroska 3D video","MNG animation","ASF video","Windows Media video","AVI video","SGI video","Atari 2600 ROM","Atari 7800 ROM","Atari Lynx ROM","Kindle book document","Partially downloaded file","WWF document","Microsoft Windows theme pack","AmazonMP3 download file","GSM 06.10 audio","iRiver playlist","Apple Keynote 5 presentation","PKCS#8 private key (encrypted)","RAML document","Sieve mail filter script","SQLite2 database","SQLite3 database","GEDCOM family history","JavaFX video","SGF record","Godot Engine scene","Godot Engine shader","GDScript script","TOML document","YAML document","Corel Draw drawing","Office Open XML Visio drawing","Office Open XML Visio template","Office Open XML Visio stencil","GNUnet search file","TNEF message","StarChart chart","StarMail email","Genesis ROM","ODT document (Flat XML)","ODG drawing (Flat XML)","ODP presentation (Flat XML)","ODS spreadsheet (Flat XML)","YouTube media archive","SPSS portable data file","SPSS data file","XBEL bookmarks","CD image cuesheet","Lotus AmiPro document","Applix Spreadsheets spreadsheet","AR archive","ARJ archive","Electron Archive (ASAR)","ASP page","AWK script","Blender scene","TeX DVI document (bzip-compressed)","Tar archive (bzip-compressed)","PDF document (bzip-compressed)","PostScript document (bzip-compressed)","Lrzip archive","Tar archive (lrzip-compressed)","Raw disk image","Floppy disk image","Raw disk image (XZ-compressed)","Compressed CD image","AppImage application bundle","CD Table Of Contents","GD-ROM image cuesheet","Padus DiscJuggler CD image","UNIX-compressed file","Tar archive (gzip-compressed)","Gzip archive","CPIO archive (gzip-compressed)","Xbase document","MAME compressed hard disk image","Nintendo DS ROM","Nintendo 3DS Executable","PC Engine ROM","Thomson Mémo7 cartridge","Thomson cassette","HFE floppy disk image","SAP Thomson floppy disk image","Qt Designer interface document","GTK+ Builder interface document","Kaitai Struct definition file","Qt Markup Language file","desktop entry","FictionBook document","Compressed FictionBook document","Dia diagram","Dia shape","Enlightenment theme","Egon Animator animation","FLTK Fluid file","Linux PSF console font (gzip-compressed)","Speedo font","TrueType XML font","Game Boy ROM","Game Boy Color ROM","Game Boy Advance ROM","Virtual Boy ROM","Genesis 32X ROM","translated messages (machine-readable)","Modelica model","Glade project","GnuCash financial data","Gnuplot document","Graphite scientific graph","TeX DVI document (gzip-compressed)","PDF document (gzip-compressed)","PostScript document (gzip-compressed)","Groovy source code","Gradle script","Java keystore","Java JCE keystore","Pack200 Java archive","JRD document","JSON patch","JSON-LD document","Jupyter notebook document","CoffeeScript document","JBuilder project","JPEG-2000 JPX image","Kexi settings","Kexi shortcut","Kexi database file","KIllustrator drawing","KPovModeler scene","Krita document","Kugar document","LHZ archive","message catalog","LyX document","LZ4 archive","Tar archive (LZ4-compressed)","Lzip archive","Tar archive (lzip-compressed)","PDF document (lzip-compressed)","LZMA archive","Tar archive (LZMA-compressed)","LZO archive","Qpress archive","Zlib archive","MHTML web archive","OCL file","COBOL source code","Internet shortcut","MSX ROM","M4 macro","Nintendo64 ROM","Neo-Geo Pocket ROM","Neo-Geo Pocket Color ROM","NES ROM","object code","Annodex exchange format","Annodex video","Annodex audio","OGM video","GNU Oleo spreadsheet","PAK archive","Parchive archive","Adobe PageMaker document","PHP script","PlanPerfect spreadsheet","Pocket Word document","Pathetic Writer document","Python bytecode","QtiPlot document","Quattro Pro spreadsheet","QuickTime playlist","Quicken document","QuickTime image","DAR archive","Alzip archive","rejected patch","RPM package","Source RPM package","Ruby script","Markaby script","Crystal source code","libtool shared library","Shorten audio","Siag spreadsheet","Skencil document","SG-1000 ROM","Master System ROM","Game Gear ROM","Super NES ROM","WebVTT subtitles","MPlayer2 subtitles","SSA subtitles","iMelody ringtone","MRML playlist","XMF audio","Mobile XMF audio","Tar archive (compressed)","generic font file","packed font file","theme","backup file","Tar archive (LZO-compressed)","Tar archive (XZ-compressed)","Zstandard archive","Tar archive (Zstandard-compressed)","PDF document (XZ-compressed)","WordPerfect/Drawperfect image","Bandai WonderSwan ROM","Bandai WonderSwan Color ROM","Zoo archive","WIM disk image","Dolby Digital audio","AMR audio","AMR-WB audio","Monkey's audio","Audible.Com audio","Audible Enhanced audio","DSDIFF audio","DSF audio","Impulse Tracker audio","WavPack audio","WavPack audio correction file","compressed Tracker audio","USAC audio","MPEG-4 ringtone","MPEG-4 audio book","MiniPSF audio","PSFlib audio library","RealVideo document","RealPix document","RealText document","Scream Tracker audio","VOC audio","Scream Tracker instrument","TrueAudio audio","HEIF image","AVIF image","MJPEG video stream","JPEG-2000 codestream","JPEG-2000 JP2 image","JPEG XL image","OpenRaster image","DirectDraw surface","EXR image","UFRaw ID image","Adobe DNG negative","Canon CRW raw image","Canon CR2 raw image","Canon CR3 raw image","Fuji RAF raw image","Kodak K25 raw image","Kodak KDC raw image","Minolta MRW raw image","Nikon NEF raw image","Nikon NRW raw image","Olympus ORF raw image","Panasonic raw image","Pentax PEF raw image","Sigma X3F raw image","Sony SRF raw image","Sony SR2 raw image","Sony ARW raw image","RLE bitmap image","Applix Graphics image","EPS image (bzip-compressed)","compressed GIMP image","DICOM image","FITS document","EPS image (gzip-compressed)","MacOS X icon","ILBM image","JNG image","LightWave object","LightWave scene","MacPaint Bitmap image","Office drawing","PCD image","Sun raster image","Windows cursor","Windows animated cursor","GIMP image","GIMP brush pipe","GIMP pattern","glTF model","OBJ 3D model material library","txt2tags document","Verilog source code","SystemVerilog header","SystemVerilog source code","VHDL source code","VHD disk image","reStructuredText document","OWL XML file","spreadsheet interchange document","WarpScript source code","Ada source code","BibTeX document","CMake source code","Common Lisp source code","CSV Schema document","C# source code","Vala source code","OOC source code","DCL script","DSSSL document","D source code","Eiffel source code","Emacs Lisp source code","Elixir source code","Erlang source code","Genie source code","translation file","Gherkin document","Google Video Pointer shortcut","Haskell source code","IDL document","LDIF address book","Lilypond music sheet","LHS source code","Makefile build file","Markdown document","Qt MOC file","Windows Registry extract","MOF file","Mup musical composition document","Objective-C source code","MATLAB file","Objective-C++ source code","Troff MM input document","OCaml source code","OpenCL source code","differences between files","Go source code","Python script","Python 3 script","SageMath script","Lua script","RPM spec file","Sass CSS pre-processor file","SCSS pre-processor file","Twig template","X-Motif UIL table","VBScript program","XMI file","XSL FO file","iptables configuration file","D-Bus service file","systemd unit file","XML entities document","DV video","ASTC texture","Haansoft Hangul document","Haansoft Hangul document template","NullSoft video","eMusic download package","GeoJSON geospatial data","Citrix ICA settings file","IT 8.7 color calibration file","CCMX color correction file","binary differences between files","TriG RDF document","Apple Numbers spreadsheet","Apple Pages document","Apple Wallet pass","Amiga disk image","Flatpak application bundle","Flatpak repository description","Flatpak repository reference","Squashfs filesystem image","Snap package","3MF document","G-code file","G-code Extended file","Nintendo FDS disk image","OVF disk image","QEMU QED disk image","QEMU QCOW disk image","VHDX disk image","VMDK disk image","VDI disk image","AppleWorks document","BPS patch","IPS patch","Pyspread spreadsheet","Pyspread spreadsheet (bzip-compressed)","Kotlin source code","Bink Video","Smacker Video","OpenZIM file"] as const

export const NOTES_DATA = [[0,1,1,1,1,1,2,4,,5,6,,,,,,,,,,,7,7,7,,,8,,9,,,10,11,11,11,11,,,,,12,12,12,,13,13,13,13,13,13,,14,14,15,16,,,,,,,,17,17,18,19,,20,20,,,,,21,21,21,22,24,25,,26,27,,,28,28,,,29,,,30,30,30,30,31,31,32,33,,35,36,37,38,,,39,40,41,,,42,43,44,44,,,46,,47,47,,,,,,,,50,51,,,,,,52,52,52,53,,,,54,55,54,56,57,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,58,,,,59,59,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,61,61,,,,,,,,,,,,,,,,,,,,,62,63,,,,,,,,,,,,,,64,,,,,65,,,,,,,,,,67,,,,,,,,,,,,,,,68,68,,,,,69,,70,,71,,72,,73,,74,,75,,76,,,,,,,,,,,,,,,79,,,,,,,,,,,80,,,,,,,,,,,,,,,,,82,,83,84,84,84,,85,,86,,84,,87,,88,88,,,,,,90,90,90,90,,92,,90,,93,,90,,94,,,21,,95,96,97,98,98,,,,,,,,,,,,,,,,,,,,99,100,101,101,102,103,104,105,106,,107,108,109,110,111,112,113,114,,,115,116,117,118,119,120,121,122,123,,124,,,125,126,125,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,128,128,,,,,129,130,131,132,132,,,133,134,135,136,137,138,139,140,141,142,,,143,,,,,146,146,146,,,,,,,,,,,147,148,148,148,,,,,,,,149,149,149,,,,,,,,,,,,,,,,,150,,,151,152,,153,154,,,,155,156,,157,157,157,158,158,159,160,160,161,,,,162,162,,163,164,165,166,166,166,,,,168,169,,,,170,171,,,172,,173,174,176,177,,178,,,179,179,179,,,180,,181,181,182,,183,184,185,186,187,188,188,188,188,189,189,183,190,,191,192,192,,193,,,,,194,,195,195,195,195,195,195,,,,,196,197,,194,194,198,198,,,199,,,,,200,201,202,203,203,204,,205,205,205,,,206,207,,,208,209,209,209,,210,210,211,212,,,,,,215,217,218,219,,,221,221,222,223,,,,,224,225,226,227,,,228,228,,,,229,229,229,242,253,255,,,259,260,261,,275,275,287,289,,305,313,314,,,,343,347,351,352,353,354,354,355,356,356,357,361,361,362,363,364,365,366,366,367,369,370,371,372,373,374,375,375,375,375,375,376,377,378,376,377,378,379,380,380,381,382,383,384,385,386,387,388,389,390,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,408,409,410,411,411,412,413,414,415,416,417,418,419,419,419,419,,420,421,,422,423,424,425,426,426,427,427,428,429,432,432,433,433,434,435,436,437,438,439,440,441,,442,443,444,445,446,447,448,450,451,452,453,454,417,455,456,,459,460,461,462,463,464,465,466,467,469,470,471,471,471,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,492,493,494,495,496,497,498,499,500,500,504,505,506,507,508,509,510,511,512,513,514,515,515,516,518,519,520,521,521,522,523,524,526,527,528,530,531,,532,533,533,541,542,543,544,545,546,547,548,549,550,551,552,553,,,554,555,,589,611,612,624,635,635,637,656,,,,693,696,696,697,697,699,700,700,701,,702,703,704,705,705,706,706,707,707,708,709,710,710,711,712,713,714,715,718,719,719,720,721,722,722,723,723,724,724,725,726,727,728,729,733],[1,21,83,84,150,195,375,332],[3,,42,42,,59,59,59,59,59,,81,127,175,,230,231,231,232,232,232,233,233,233,233,233,234,234,236,237,237,237,238,238,236,239,243,244,,245,,,,,246,246,247,247,,,,,,,,248,248,249,250,250,,251,251,252,,253,254,254,127,127,,,256,256,256,,257,290,333,333,333,333,333,333,334,,358,359,360,502,502,527,537,537,539,539,540,540,556,557,557,558,558,559,560,560,561,562,562,563,563,563,563,564,565,566,567,568,569,570,571,572,576,577,578,579,579],[14,23,,34,46,48,50,51,60,66,77,78,91,91,191,206,208,213,213,214,225,227,,278,279,280,289,304,305,305,306,307,307,307,308,,309,,310,311,,312,313,313,314,315,316,317,,318,318,318,,,,,,,,,319,320,321,,322,322,323,324,325,326,,327,328,329,329,330,331,,332,18,367,374,374,,8,430,431,449,457,458,477,477,478,490,491,,520,525,525,534,535,536,537,538,575,630,631,632,633,634,636,,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,656,657,658,658,659,660,661,662,663,664,665,665,666,667,668,669,670,671,671,672,673,674,675,676,676,677,678,679,680,681,682,683,684,685,686,687,687,688,689,690,691,692,693,716,717,730],[30,45,49,148,148,148,148,148,167,194,194,194,198,198,220,263,263,263,264,265,265,266,267,268,268,269,270,,,271,,272,273,274,275,275,275,275,275,,276,276,276,277,,281,282,,,,,,283,,,284,,285,286,288,,,289,289,289,289,289,,291,291,292,293,294,295,296,297,298,299,299,300,335,375,375,468,517,529,574,580,580,580,580,581,583,584,584,584,584,585,586,587,588,,590,591,592,593,594,595,596,597,598,599,600,601,601,601,601,602,603,604,605,606,607,608,609,610,612,612,613,614,615,615,616,617,618,619,620,621,622,623,625,626,627,269,695,581],[89,89,89,216,302,,,,,,,,303,,,,,,628,628,629,715],[144],[145,235,235,235,235,235,240,240,241,241,253,253,253,333,333,333,334,,,,,,336,337,337,337,338,,,,,,,,339,339,,,,340,340,341,,342,342,342,343,343,344,345,346,347,347,347,,348,349,349,349,349,349,349,350,,368,,501,501,503,503,573,573,582,694,698,731,732],[],[258,259,260,261,262],[301],[343],[],[]] as const

export type TypeNOTES = {
  "application/x-atari-2600-rom": "Atari 2600 ROM",
  "application/x-atari-7800-rom": "Atari 7800 ROM",
  "application/x-atari-lynx-rom": "Atari Lynx ROM",
  "application/andrew-inset": "ATK inset",
  "application/epub+zip": "electronic book document",
  "application/vnd.amazon.mobi8-ebook": "Kindle book document",
  "application/x-mobi8-ebook": "Kindle book document",
  "application/illustrator": "Adobe Illustrator document",
  "application/vnd.adobe.illustrator": "Adobe Illustrator document",
  "application/mathematica": "Mathematica Notebook file",
  "application/x-mathematica": "Mathematica Notebook file",
  "application/mathml+xml": "MathML document",
  "text/mathml": "MathML document",
  "application/mbox": "mailbox file",
  "application/metalink+xml": "Metalink file",
  "application/metalink4+xml": "Metalink file",
  "application/x-partial-download": "Partially downloaded file",
  "application/oda": "ODA document",
  "application/x-wwf": "WWF document",
  "application/wwf": "WWF document",
  "application/pdf": "PDF document",
  "application/x-pdf": "PDF document",
  "image/pdf": "PDF document",
  "application/acrobat": "PDF document",
  "application/nappdf": "PDF document",
  "application/xspf+xml": "XSPF playlist",
  "application/x-xspf+xml": "XSPF playlist",
  "application/x-windows-themepack": "Microsoft Windows theme pack",
  "audio/x-amzxml": "AmazonMP3 download file",
  "audio/x-gsm": "GSM 06.10 audio",
  "audio/x-iriver-pla": "iRiver playlist",
  "application/pgp-encrypted": "PGP/MIME-encrypted message header",
  "application/pgp": "PGP/MIME-encrypted message header",
  "application/pgp-keys": "PGP keys",
  "application/pgp-signature": "detached OpenPGP signature",
  "application/pkcs7-mime": "PKCS#7 file",
  "application/pkcs7-signature": "detached S/MIME signature",
  "application/pkcs8": "PKCS#8 private key",
  "application/pkcs8-encrypted": "PKCS#8 private key (encrypted)",
  "application/pkcs10": "PKCS#10 certification request",
  "application/pkix-cert": "X.509 certificate",
  "application/pkix-crl": "certificate revocation list",
  "application/pkix-pkipath": "PkiPath certification path",
  "application/postscript": "PostScript document",
  "application/raml+yaml": "RAML document",
  "application/relax-ng-compact-syntax": "RELAX NG XML schema",
  "application/x-rnc": "RELAX NG XML schema",
  "application/rtf": "RTF document",
  "text/rtf": "RTF document",
  "application/sieve": "Sieve mail filter script",
  "application/smil+xml": "SMIL document",
  "application/smil": "SMIL document",
  "application/vnd.ms-wpl": "WPL playlist",
  "application/x-sqlite2": "SQLite2 database",
  "application/vnd.sqlite3": "SQLite3 database",
  "application/x-sqlite3": "SQLite3 database",
  "application/x-apple-systemprofiler+xml": "Apple System Profiler",
  "application/x-gedcom": "GEDCOM family history",
  "text/gedcom": "GEDCOM family history",
  "video/x-flv": "Flash video",
  "application/x-flash-video": "Flash video",
  "flv-application/octet-stream": "Flash video",
  "video/flv": "Flash video",
  "video/x-javafx": "JavaFX video",
  "application/x-go-sgf": "SGF record",
  "application/x-godot-resource": "Godot Engine resource",
  "application/x-godot-scene": "Godot Engine scene",
  "application/x-godot-shader": "Godot Engine shader",
  "application/x-gdscript": "GDScript script",
  "application/xliff+xml": "XLIFF translation file",
  "application/x-xliff": "XLIFF translation file",
  "application/toml": "TOML document",
  "application/x-yaml": "YAML document",
  "text/yaml": "YAML document",
  "text/x-yaml": "YAML document",
  "application/vnd.corel-draw": "Corel Draw drawing",
  "application/cdr": "Corel Draw drawing",
  "application/coreldraw": "Corel Draw drawing",
  "application/x-cdr": "Corel Draw drawing",
  "application/x-coreldraw": "Corel Draw drawing",
  "image/cdr": "Corel Draw drawing",
  "image/x-cdr": "Corel Draw drawing",
  "zz-application/zz-winassoc-cdr": "Corel Draw drawing",
  "application/vnd.hp-hpgl": "HPGL file",
  "application/vnd.hp-pcl": "PCL file",
  "application/vnd.lotus-1-2-3": "Lotus 1-2-3 spreadsheet",
  "application/x-lotus123": "Lotus 1-2-3 spreadsheet",
  "application/x-123": "Lotus 1-2-3 spreadsheet",
  "application/lotus123": "Lotus 1-2-3 spreadsheet",
  "application/wk1": "Lotus 1-2-3 spreadsheet",
  "zz-application/zz-winassoc-123": "Lotus 1-2-3 spreadsheet",
  "application/vnd.lotus-wordpro": "Lotus Word Pro document",
  "application/vnd.ms-access": "JET database",
  "application/msaccess": "JET database",
  "application/vnd.msaccess": "JET database",
  "application/x-msaccess": "JET database",
  "application/mdb": "JET database",
  "application/x-mdb": "JET database",
  "zz-application/zz-winassoc-mdb": "JET database",
  "application/vnd.ms-cab-compressed": "Microsoft Cabinet archive",
  "zz-application/zz-winassoc-cab": "Microsoft Cabinet archive",
  "application/vnd.ms-excel": "Excel spreadsheet",
  "application/msexcel": "Excel spreadsheet",
  "application/x-msexcel": "Excel spreadsheet",
  "zz-application/zz-winassoc-xls": "Excel spreadsheet",
  "application/vnd.ms-excel.addin.macroEnabled.12": "Excel add-in",
  "application/vnd.ms-excel.sheet.binary.macroEnabled.12": "Excel 2007 binary spreadsheet",
  "application/vnd.ms-excel.sheet.macroEnabled.12": "Excel spreadsheet",
  "application/vnd.ms-excel.template.macroEnabled.12": "Excel spreadsheet template",
  "application/vnd.ms-powerpoint": "PowerPoint presentation",
  "application/powerpoint": "PowerPoint presentation",
  "application/mspowerpoint": "PowerPoint presentation",
  "application/x-mspowerpoint": "PowerPoint presentation",
  "application/vnd.ms-powerpoint.addin.macroEnabled.12": "PowerPoint add-in",
  "application/vnd.ms-powerpoint.presentation.macroEnabled.12": "PowerPoint presentation",
  "application/vnd.ms-powerpoint.slide.macroEnabled.12": "PowerPoint slide",
  "application/vnd.ms-powerpoint.slideshow.macroEnabled.12": "PowerPoint presentation",
  "application/vnd.ms-powerpoint.template.macroEnabled.12": "PowerPoint presentation template",
  "application/vnd.ms-visio.drawing.main+xml": "Office Open XML Visio drawing",
  "application/vnd.ms-visio.template.main+xml": "Office Open XML Visio template",
  "application/vnd.ms-visio.stencil.main+xml": "Office Open XML Visio stencil",
  "application/vnd.ms-visio.drawing.macroEnabled.main+xml": "Office Open XML Visio drawing",
  "application/vnd.ms-visio.template.macroEnabled.main+xml": "Office Open XML Visio template",
  "application/vnd.ms-visio.stencil.macroEnabled.main+xml": "Office Open XML Visio stencil",
  "application/vnd.ms-word.document.macroEnabled.12": "Word document",
  "application/vnd.ms-word.template.macroEnabled.12": "Word document template",
  "application/oxps": "OpenXPS document",
  "application/vnd.ms-xpsdocument": "XPS document",
  "application/xps": "XPS document",
  "application/vnd.ms-works": "Microsoft Works document",
  "application/vnd.visio": "Microsoft Visio document",
  "application/msword": "Word document",
  "application/vnd.ms-word": "Word document",
  "application/x-msword": "Word document",
  "zz-application/zz-winassoc-doc": "Word document",
  "application/msword-template": "Word template",
  "application/gml+xml": "GML document",
  "application/gnunet-directory": "GNUnet search file",
  "application/vnd.ms-tnef": "TNEF message",
  "application/ms-tnef": "TNEF message",
  "application/vnd.stardivision.calc": "StarCalc spreadsheet",
  "application/vnd.stardivision.chart": "StarChart chart",
  "application/vnd.stardivision.draw": "StarDraw drawing",
  "application/vnd.stardivision.impress": "StarImpress presentation",
  "application/vnd.stardivision.mail": "StarMail email",
  "application/vnd.stardivision.math": "StarMath formula",
  "application/vnd.stardivision.writer": "StarWriter document",
  "application/vnd.stardivision.writer-global": "StarWriter document",
  "application/vnd.sun.xml.calc": "OpenOffice Calc spreadsheet",
  "application/vnd.sun.xml.calc.template": "OpenOffice Calc template",
  "application/vnd.sun.xml.draw": "OpenOffice Draw drawing",
  "application/vnd.sun.xml.draw.template": "OpenOffice Draw template",
  "application/vnd.sun.xml.impress": "OpenOffice Impress presentation",
  "application/vnd.sun.xml.impress.template": "OpenOffice Impress template",
  "application/vnd.sun.xml.math": "OpenOffice Math formula",
  "application/vnd.sun.xml.writer": "OpenOffice Writer document",
  "application/vnd.sun.xml.writer.global": "OpenOffice Writer global document",
  "application/vnd.sun.xml.writer.template": "OpenOffice Writer template",
  "application/vnd.oasis.opendocument.text": "ODT document",
  "application/vnd.oasis.opendocument.text-flat-xml": "ODT document (Flat XML)",
  "application/vnd.oasis.opendocument.text-template": "ODT template",
  "application/vnd.oasis.opendocument.text-web": "OTH template",
  "application/vnd.oasis.opendocument.text-master": "ODM document",
  "application/vnd.oasis.opendocument.graphics": "ODG drawing",
  "application/vnd.oasis.opendocument.graphics-flat-xml": "ODG drawing (Flat XML)",
  "application/vnd.oasis.opendocument.graphics-template": "ODG template",
  "application/vnd.oasis.opendocument.presentation": "ODP presentation",
  "application/vnd.oasis.opendocument.presentation-flat-xml": "ODP presentation (Flat XML)",
  "application/vnd.oasis.opendocument.presentation-template": "ODP template",
  "application/vnd.oasis.opendocument.spreadsheet": "ODS spreadsheet",
  "application/vnd.oasis.opendocument.spreadsheet-flat-xml": "ODS spreadsheet (Flat XML)",
  "application/vnd.oasis.opendocument.spreadsheet-template": "ODS template",
  "application/vnd.oasis.opendocument.chart": "ODC chart",
  "application/vnd.oasis.opendocument.chart-template": "ODC template",
  "application/vnd.oasis.opendocument.formula": "ODF formula",
  "application/vnd.oasis.opendocument.formula-template": "ODF template",
  "application/vnd.oasis.opendocument.database": "ODB database",
  "application/vnd.sun.xml.base": "ODB database",
  "application/vnd.oasis.opendocument.image": "ODI image",
  "application/vnd.openofficeorg.extension": "OpenOffice.org extension",
  "application/vnd.android.package-archive": "Android package",
  "application/vnd.symbian.install": "SIS package",
  "x-epoc/x-sisx-app": "SISX package",
  "application/vnd.tcpdump.pcap": "network packet capture",
  "application/x-pcap": "network packet capture",
  "application/pcap": "network packet capture",
  "application/vnd.wordperfect": "WordPerfect document",
  "application/x-wordperfect": "WordPerfect document",
  "application/wordperfect": "WordPerfect document",
  "application/vnd.youtube.yt": "YouTube media archive",
  "application/x-spss-por": "SPSS portable data file",
  "application/x-spss-sav": "SPSS data file",
  "application/x-spss-savefile": "SPSS data file",
  "application/x-xbel": "XBEL bookmarks",
  "application/x-7z-compressed": "7-zip archive",
  "application/x-abiword": "AbiWord document",
  "application/x-cue": "CD image cuesheet",
  "application/x-amipro": "Lotus AmiPro document",
  "application/x-aportisdoc": "AportisDoc document",
  "application/x-applix-spreadsheet": "Applix Spreadsheets spreadsheet",
  "application/x-applix-word": "Applix Words document",
  "application/x-archive": "AR archive",
  "application/x-arj": "ARJ archive",
  "application/x-asar": "Electron Archive (ASAR)",
  "application/x-asp": "ASP page",
  "application/x-awk": "AWK script",
  "application/x-bcpio": "BCPIO archive",
  "application/x-bittorrent": "BitTorrent seed file",
  "application/x-blender": "Blender scene",
  "application/x-bzdvi": "TeX DVI document (bzip-compressed)",
  "application/x-bzip": "Bzip archive",
  "application/x-bzip2": "Bzip archive",
  "application/bzip2": "Bzip archive",
  "application/x-bzip-compressed-tar": "Tar archive (bzip-compressed)",
  "application/x-bzpdf": "PDF document (bzip-compressed)",
  "application/x-bzpostscript": "PostScript document (bzip-compressed)",
  "application/vnd.comicbook-rar": "comic book archive (rar container)",
  "application/x-cbr": "comic book archive (rar container)",
  "application/x-cb7": "comic book archive (7z container)",
  "application/x-cbt": "comic book archive (tar container)",
  "application/vnd.comicbook+zip": "comic book archive (zip container)",
  "application/x-cbz": "comic book archive (zip container)",
  "application/x-lrzip": "Lrzip archive",
  "application/x-lrzip-compressed-tar": "Tar archive (lrzip-compressed)",
  "application/x-apple-diskimage": "Apple disk image",
  "application/x-raw-disk-image": "Raw disk image",
  "application/x-raw-floppy-disk-image": "Floppy disk image",
  "application/x-fd-file": "Floppy disk image",
  "application/x-raw-disk-image-xz-compressed": "Raw disk image (XZ-compressed)",
  "application/x-cd-image": "raw CD image",
  "application/x-iso9660-image": "raw CD image",
  "application/x-compressed-iso": "Compressed CD image",
  "application/x-iso9660-appimage": "AppImage application bundle",
  "application/x-cdrdao-toc": "CD Table Of Contents",
  "application/x-gd-rom-cue": "GD-ROM image cuesheet",
  "application/x-discjuggler-cd-image": "Padus DiscJuggler CD image",
  "application/vnd.chess-pgn": "PGN chess game notation",
  "application/x-chess-pgn": "PGN chess game notation",
  "application/vnd.ms-htmlhelp": "CHM document",
  "application/x-chm": "CHM document",
  "application/x-compress": "UNIX-compressed file",
  "application/x-compressed-tar": "Tar archive (gzip-compressed)",
  "application/x-cpio": "CPIO archive",
  "application/x-cpio-compressed": "CPIO archive (gzip-compressed)",
  "application/x-csh": "C shell script",
  "application/x-dbf": "Xbase document",
  "application/x-dbase": "Xbase document",
  "application/dbf": "Xbase document",
  "application/dbase": "Xbase document",
  "application/ecmascript": "ECMAScript program",
  "text/ecmascript": "ECMAScript program",
  "application/x-mame-chd": "MAME compressed hard disk image",
  "application/x-sega-cd-rom": "Sega CD disc image",
  "application/x-sega-pico-rom": "Sega Pico ROM",
  "application/x-saturn-rom": "Sega Saturn disc image",
  "application/x-dreamcast-rom": "Dreamcast disc image",
  "application/x-nintendo-ds-rom": "Nintendo DS ROM",
  "application/x-nintendo-3ds-rom": "Nintendo 3DS ROM",
  "application/x-nintendo-3ds-executable": "Nintendo 3DS Executable",
  "application/x-pc-engine-rom": "PC Engine ROM",
  "application/x-wii-rom": "Wii disc image",
  "application/x-wii-iso-image": "Wii disc image",
  "application/x-wbfs": "Wii disc image",
  "application/x-wia": "Wii disc image",
  "application/x-wii-wad": "WiiWare bundle",
  "application/x-gamecube-rom": "GameCube disc image",
  "application/x-gamecube-iso-image": "GameCube disc image",
  "application/x-thomson-cartridge-memo7": "Thomson Mémo7 cartridge",
  "application/x-thomson-cassette": "Thomson cassette",
  "application/x-hfe-floppy-image": "HFE floppy disk image",
  "application/x-hfe-file": "HFE floppy disk image",
  "application/x-thomson-sap-image": "SAP Thomson floppy disk image",
  "application/x-sap-file": "SAP Thomson floppy disk image",
  "application/vnd.debian.binary-package": "Debian package",
  "application/x-deb": "Debian package",
  "application/x-debian-package": "Debian package",
  "application/x-designer": "Qt Designer interface document",
  "text/x-kaitai-struct": "Kaitai Struct definition file",
  "text/x-qml": "Qt Markup Language file",
  "application/x-desktop": "desktop entry",
  "application/x-gnome-app-info": "desktop entry",
  "application/x-fictionbook+xml": "FictionBook document",
  "application/x-fictionbook": "FictionBook document",
  "application/x-zip-compressed-fb2": "Compressed FictionBook document",
  "application/x-dia-diagram": "Dia diagram",
  "application/x-dia-shape": "Dia shape",
  "application/x-dvi": "TeX DVI document",
  "application/x-e-theme": "Enlightenment theme",
  "application/x-egon": "Egon Animator animation",
  "application/x-fluid": "FLTK Fluid file",
  "font/woff": "WOFF font",
  "application/font-woff": "WOFF font",
  "font/woff2": "WOFF2 font",
  "application/x-font-type1": "PostScript type-1 font",
  "application/x-font-afm": "Adobe font metrics",
  "application/x-font-bdf": "BDF font",
  "application/x-font-linux-psf": "Linux PSF console font",
  "application/x-gz-font-linux-psf": "Linux PSF console font (gzip-compressed)",
  "application/x-font-pcf": "PCF font",
  "font/otf": "OpenType font",
  "application/x-font-otf": "OpenType font",
  "application/x-font-speedo": "Speedo font",
  "font/ttf": "TrueType font",
  "application/x-font-ttf": "TrueType font",
  "font/collection": "Font collection",
  "application/x-font-ttx": "TrueType XML font",
  "application/vnd.framemaker": "Adobe FrameMaker document",
  "application/x-frame": "Adobe FrameMaker document",
  "application/x-gameboy-rom": "Game Boy ROM",
  "application/x-gameboy-color-rom": "Game Boy Color ROM",
  "application/x-gba-rom": "Game Boy Advance ROM",
  "application/x-virtual-boy-rom": "Virtual Boy ROM",
  "application/x-genesis-rom": "Genesis ROM",
  "application/x-genesis-32x-rom": "Genesis 32X ROM",
  "application/x-gettext-translation": "translated messages (machine-readable)",
  "application/x-gtk-builder": "GTK+ Builder interface document",
  "application/x-glade": "Glade project",
  "application/x-gnucash": "GnuCash financial data",
  "application/x-gnumeric": "Gnumeric spreadsheet",
  "application/x-gnuplot": "Gnuplot document",
  "application/x-graphite": "Graphite scientific graph",
  "application/x-gzdvi": "TeX DVI document (gzip-compressed)",
  "application/gzip": "Gzip archive",
  "application/x-gzip": "Gzip archive",
  "application/x-gzpdf": "PDF document (gzip-compressed)",
  "application/x-gzpostscript": "PostScript document (gzip-compressed)",
  "application/x-hdf": "HDF document",
  "application/x-java-archive": "Java archive",
  "application/x-jar": "Java archive",
  "application/java-archive": "Java archive",
  "application/x-java": "Java class",
  "application/java": "Java class",
  "application/java-byte-code": "Java class",
  "application/java-vm": "Java class",
  "application/x-java-class": "Java class",
  "application/x-java-vm": "Java class",
  "text/x-groovy": "Groovy source code",
  "text/x-gradle": "Gradle script",
  "application/x-java-jnlp-file": "JNLP file",
  "application/x-java-keystore": "Java keystore",
  "application/x-java-jce-keystore": "Java JCE keystore",
  "application/x-java-pack200": "Pack200 Java archive",
  "application/javascript": "JavaScript program",
  "application/x-javascript": "JavaScript program",
  "text/javascript": "JavaScript program",
  "application/json": "JSON document",
  "application/jrd+json": "JRD document",
  "application/json-patch+json": "JSON patch",
  "application/ld+json": "JSON-LD document",
  "application/schema+json": "JSON schema",
  "application/x-ipynb+json": "Jupyter notebook document",
  "application/vnd.coffeescript": "CoffeeScript document",
  "application/x-jbuilder-project": "JBuilder project",
  "application/x-karbon": "Karbon14 drawing",
  "application/x-kchart": "KChart chart",
  "application/x-kexi-connectiondata": "Kexi settings",
  "application/x-kexiproject-shortcut": "Kexi shortcut",
  "application/x-kexiproject-sqlite2": "Kexi database file",
  "application/x-kexiproject-sqlite3": "Kexi database file",
  "application/x-vnd.kde.kexi": "Kexi database file",
  "application/x-kexiproject-sqlite": "Kexi database file",
  "application/x-kformula": "KFormula formula",
  "application/x-killustrator": "KIllustrator drawing",
  "application/x-kivio": "Kivio flowchart",
  "application/x-kontour": "Kontour drawing",
  "application/x-kpovmodeler": "KPovModeler scene",
  "application/x-kpresenter": "KPresenter presentation",
  "application/x-krita": "Krita document",
  "application/x-kspread": "KSpread spreadsheet",
  "application/x-kugar": "Kugar document",
  "application/x-kword": "KWord document",
  "application/x-lha": "LHA archive",
  "application/x-lzh-compressed": "LHA archive",
  "application/x-lhz": "LHZ archive",
  "text/vnd.trolltech.linguist": "message catalog",
  "application/x-linguist": "message catalog",
  "text/vnd.qt.linguist": "message catalog",
  "application/x-lyx": "LyX document",
  "text/x-lyx": "LyX document",
  "application/x-lz4": "LZ4 archive",
  "application/x-lz4-compressed-tar": "Tar archive (LZ4-compressed)",
  "application/x-lzip": "Lzip archive",
  "application/x-lzip-compressed-tar": "Tar archive (lzip-compressed)",
  "application/x-lzpdf": "PDF document (lzip-compressed)",
  "application/x-lzma": "LZMA archive",
  "application/x-lzma-compressed-tar": "Tar archive (LZMA-compressed)",
  "application/x-lzop": "LZO archive",
  "application/x-qpress": "Qpress archive",
  "application/x-xar": "XAR archive",
  "application/zlib": "Zlib archive",
  "application/x-magicpoint": "MagicPoint presentation",
  "video/x-matroska": "Matroska video",
  "video/x-matroska-3d": "Matroska 3D video",
  "audio/x-matroska": "Matroska audio",
  "video/webm": "WebM video",
  "application/x-mimearchive": "MHTML web archive",
  "application/mxf": "MXF video",
  "text/x-ocl": "OCL file",
  "text/x-cobol": "COBOL source code",
  "application/x-mobipocket-ebook": "Mobipocket e-book",
  "application/x-mif": "Adobe FrameMaker MIF document",
  "application/x-ms-dos-executable": "DOS/Windows executable",
  "application/x-mswinurl": "Internet shortcut",
  "application/x-mswrite": "WRI document",
  "application/x-msx-rom": "MSX ROM",
  "application/x-m4": "M4 macro",
  "application/x-n64-rom": "Nintendo64 ROM",
  "application/x-neo-geo-pocket-rom": "Neo-Geo Pocket ROM",
  "application/x-neo-geo-pocket-color-rom": "Neo-Geo Pocket Color ROM",
  "application/x-nes-rom": "NES ROM",
  "application/x-netcdf": "Unidata NetCDF document",
  "application/x-nzb": "NewzBin usenet index",
  "application/x-object": "object code",
  "application/annodex": "Annodex exchange format",
  "application/x-annodex": "Annodex exchange format",
  "video/annodex": "Annodex video",
  "video/x-annodex": "Annodex video",
  "audio/annodex": "Annodex audio",
  "audio/x-annodex": "Annodex audio",
  "application/ogg": "Ogg multimedia file",
  "application/x-ogg": "Ogg multimedia file",
  "audio/ogg": "Ogg audio",
  "audio/x-ogg": "Ogg audio",
  "video/ogg": "Ogg video",
  "video/x-ogg": "Ogg video",
  "audio/x-vorbis+ogg": "Ogg Vorbis audio",
  "audio/vorbis": "Ogg Vorbis audio",
  "audio/x-vorbis": "Ogg Vorbis audio",
  "audio/x-flac+ogg": "Ogg FLAC audio",
  "audio/x-oggflac": "Ogg FLAC audio",
  "audio/x-opus+ogg": "Opus audio",
  "audio/x-speex+ogg": "Ogg Speex audio",
  "audio/x-speex": "Speex audio",
  "video/x-theora+ogg": "Ogg Theora video",
  "video/x-theora": "Ogg Theora video",
  "video/x-ogm+ogg": "OGM video",
  "video/x-ogm": "OGM video",
  "application/vnd.ms-publisher": "Microsoft Publisher document",
  "application/x-msi": "Windows Installer package",
  "application/x-oleo": "GNU Oleo spreadsheet",
  "application/x-pak": "PAK archive",
  "application/vnd.palm": "Palm OS database",
  "application/x-palm-database": "Palm OS database",
  "application/x-par2": "Parchive archive",
  "application/x-perl": "Perl script",
  "text/x-perl": "Perl script",
  "application/x-php": "PHP script",
  "application/x-pkcs7-certificates": "PKCS#7 certificate bundle",
  "application/pkcs12": "PKCS#12 certificate bundle",
  "application/x-pkcs12": "PKCS#12 certificate bundle",
  "application/x-planperfect": "PlanPerfect spreadsheet",
  "application/x-pocket-word": "Pocket Word document",
  "application/x-pw": "Pathetic Writer document",
  "application/x-python-bytecode": "Python bytecode",
  "application/x-qtiplot": "QtiPlot document",
  "application/x-quattropro": "Quattro Pro spreadsheet",
  "application/x-quicktime-media-link": "QuickTime playlist",
  "application/x-quicktimeplayer": "QuickTime playlist",
  "application/x-qw": "Quicken document",
  "application/vnd.rar": "RAR archive",
  "application/x-rar": "RAR archive",
  "application/x-rar-compressed": "RAR archive",
  "application/x-dar": "DAR archive",
  "application/x-alz": "Alzip archive",
  "text/x-reject": "rejected patch",
  "application/x-reject": "rejected patch",
  "application/x-rpm": "RPM package",
  "application/x-redhat-package-manager": "RPM package",
  "application/x-source-rpm": "Source RPM package",
  "application/x-ruby": "Ruby script",
  "application/x-markaby": "Markaby script",
  "text/x-crystal": "Crystal source code",
  "text/crystal": "Crystal source code",
  "text/rust": "Rust source code",
  "application/x-shar": "shell archive",
  "application/x-shared-library-la": "libtool shared library",
  "application/x-sharedlib": "shared library",
  "application/x-shellscript": "shell script",
  "text/x-sh": "shell script",
  "application/vnd.adobe.flash.movie": "Shockwave Flash file",
  "application/x-shockwave-flash": "Shockwave Flash file",
  "application/futuresplash": "Shockwave Flash file",
  "application/x-shorten": "Shorten audio",
  "audio/x-shorten": "Shorten audio",
  "application/x-siag": "Siag spreadsheet",
  "image/x-skencil": "Skencil document",
  "application/x-sg1000-rom": "SG-1000 ROM",
  "application/x-sms-rom": "Master System ROM",
  "application/x-gamegear-rom": "Game Gear ROM",
  "application/vnd.nintendo.snes.rom": "Super NES ROM",
  "application/x-snes-rom": "Super NES ROM",
  "application/x-stuffit": "StuffIt archive",
  "application/stuffit": "StuffIt archive",
  "application/x-sit": "StuffIt archive",
  "application/x-subrip": "SubRip subtitles",
  "application/x-srt": "SubRip subtitles",
  "text/vtt": "WebVTT subtitles",
  "application/x-sami": "SAMI subtitles",
  "text/x-microdvd": "MicroDVD subtitles",
  "text/x-mpl2": "MPlayer2 subtitles",
  "text/x-mpsub": "MPSub subtitles",
  "text/x-ssa": "SSA subtitles",
  "text/x-subviewer": "SubViewer subtitles",
  "text/x-iMelody": "iMelody ringtone",
  "audio/x-iMelody": "iMelody ringtone",
  "audio/iMelody": "iMelody ringtone",
  "application/vnd.smaf": "SMAF audio",
  "application/x-smaf": "SMAF audio",
  "text/x-mrml": "MRML playlist",
  "audio/x-xmf": "XMF audio",
  "audio/xmf": "XMF audio",
  "audio/mobile-xmf": "Mobile XMF audio",
  "audio/vnd.nokia.mobile-xmf": "Mobile XMF audio",
  "application/x-sv4cpio": "SV4 CPIO archive",
  "application/x-sv4crc": "SV4 CPIO archive (with CRC)",
  "application/x-tar": "Tar archive",
  "application/x-gtar": "Tar archive",
  "application/x-tarz": "Tar archive (compressed)",
  "application/x-tex-gf": "generic font file",
  "application/x-tex-pk": "packed font file",
  "application/x-tgif": "TGIF document",
  "application/x-theme": "theme",
  "application/x-trash": "backup file",
  "text/troff": "Troff document",
  "application/x-troff": "Troff document",
  "text/x-troff": "Troff document",
  "application/x-troff-man": "Manual page",
  "application/x-tzo": "Tar archive (LZO-compressed)",
  "application/x-xz": "XZ archive",
  "application/x-xz-compressed-tar": "Tar archive (XZ-compressed)",
  "application/zstd": "Zstandard archive",
  "application/x-zstd-compressed-tar": "Tar archive (Zstandard-compressed)",
  "application/x-xzpdf": "PDF document (XZ-compressed)",
  "application/x-ustar": "Ustar archive",
  "application/x-wais-source": "WAIS source code",
  "application/x-wpg": "WordPerfect/Drawperfect image",
  "application/x-wonderswan-rom": "Bandai WonderSwan ROM",
  "application/x-wonderswan-color-rom": "Bandai WonderSwan Color ROM",
  "application/x-x509-ca-cert": "DER/PEM/Netscape-encoded X.509 certificate",
  "application/x-zoo": "Zoo archive",
  "application/xhtml+xml": "XHTML page",
  "application/zip": "Zip archive",
  "application/x-zip-compressed": "Zip archive",
  "application/x-zip": "Zip archive",
  "application/x-ms-wim": "WIM disk image",
  "audio/ac3": "Dolby Digital audio",
  "audio/vnd.dts": "DTS audio",
  "audio/x-dts": "DTS audio",
  "audio/vnd.dts.hd": "DTS-HD audio",
  "audio/x-dtshd": "DTS-HD audio",
  "audio/AMR": "AMR audio",
  "audio/amr-encrypted": "AMR audio",
  "audio/AMR-WB": "AMR-WB audio",
  "audio/amr-wb-encrypted": "AMR-WB audio",
  "audio/basic": "ULAW (Sun) audio",
  "audio/prs.sid": "Commodore 64 audio",
  "audio/x-aifc": "AIFC audio",
  "audio/x-aiffc": "AIFC audio",
  "audio/x-aiff": "AIFF/Amiga/Mac audio",
  "audio/x-ape": "Monkey's audio",
  "audio/x-pn-audibleaudio": "Audible.Com audio",
  "audio/vnd.audible": "Audible.Com audio",
  "audio/vnd.audible.aax": "Audible Enhanced audio",
  "audio/x-dff": "DSDIFF audio",
  "audio/dff": "DSDIFF audio",
  "audio/x-dsf": "DSF audio",
  "audio/dsf": "DSF audio",
  "audio/x-dsd": "DSF audio",
  "audio/dsd": "DSF audio",
  "audio/x-it": "Impulse Tracker audio",
  "audio/flac": "FLAC audio",
  "audio/x-flac": "FLAC audio",
  "audio/x-wavpack": "WavPack audio",
  "audio/x-wavpack-correction": "WavPack audio correction file",
  "audio/midi": "MIDI audio",
  "audio/x-midi": "MIDI audio",
  "audio/x-mo3": "compressed Tracker audio",
  "audio/aac": "AAC audio",
  "audio/x-aac": "AAC audio",
  "audio/usac": "USAC audio",
  "audio/mp4": "MPEG-4 audio",
  "audio/x-m4a": "MPEG-4 audio",
  "audio/m4a": "MPEG-4 audio",
  "audio/x-m4r": "MPEG-4 ringtone",
  "video/mp4": "MPEG-4 video",
  "video/mp4v-es": "MPEG-4 video",
  "video/x-m4v": "MPEG-4 video",
  "audio/x-m4b": "MPEG-4 audio book",
  "video/3gpp": "3GPP multimedia file",
  "video/3gp": "3GPP multimedia file",
  "audio/3gpp": "3GPP multimedia file",
  "video/3gpp-encrypted": "3GPP multimedia file",
  "audio/3gpp-encrypted": "3GPP multimedia file",
  "audio/x-rn-3gpp-amr": "3GPP multimedia file",
  "audio/x-rn-3gpp-amr-encrypted": "3GPP multimedia file",
  "audio/x-rn-3gpp-amr-wb": "3GPP multimedia file",
  "audio/x-rn-3gpp-amr-wb-encrypted": "3GPP multimedia file",
  "video/3gpp2": "3GPP2 multimedia file",
  "audio/3gpp2": "3GPP2 multimedia file",
  "audio/x-mod": "Amiga SoundTracker audio",
  "audio/mp2": "MP2 audio",
  "audio/x-mp2": "MP2 audio",
  "audio/mpeg": "MP3 audio",
  "audio/x-mp3": "MP3 audio",
  "audio/x-mpg": "MP3 audio",
  "audio/x-mpeg": "MP3 audio",
  "audio/mp3": "MP3 audio",
  "audio/x-mpegurl": "Media playlist",
  "audio/mpegurl": "Media playlist",
  "application/m3u": "Media playlist",
  "audio/x-mp3-playlist": "Media playlist",
  "audio/m3u": "Media playlist",
  "audio/x-m3u": "Media playlist",
  "application/vnd.apple.mpegurl": "Media playlist",
  "audio/x-ms-asx": "Microsoft ASX playlist",
  "video/x-ms-wvx": "Microsoft ASX playlist",
  "video/x-ms-wax": "Microsoft ASX playlist",
  "video/x-ms-wmx": "Microsoft ASX playlist",
  "application/x-ms-asx": "Microsoft ASX playlist",
  "audio/x-psf": "PSF audio",
  "audio/x-minipsf": "MiniPSF audio",
  "audio/x-psflib": "PSFlib audio library",
  "audio/x-ms-wma": "Windows Media audio",
  "audio/wma": "Windows Media audio",
  "audio/x-musepack": "Musepack audio",
  "audio/vnd.rn-realaudio": "RealAudio document",
  "audio/x-pn-realaudio": "RealAudio document",
  "audio/vnd.m-realaudio": "RealAudio document",
  "application/ram": "RealMedia playlist",
  "video/vnd.rn-realvideo": "RealVideo document",
  "video/x-real-video": "RealVideo document",
  "application/vnd.rn-realmedia": "RealMedia document",
  "application/vnd.rn-realmedia-vbr": "RealMedia document",
  "image/vnd.rn-realpix": "RealPix document",
  "text/vnd.rn-realtext": "RealText document",
  "audio/x-s3m": "Scream Tracker 3 audio",
  "audio/x-scpls": "MP3 ShoutCast playlist",
  "application/pls": "MP3 ShoutCast playlist",
  "audio/scpls": "MP3 ShoutCast playlist",
  "audio/x-stm": "Scream Tracker audio",
  "audio/x-voc": "VOC audio",
  "audio/x-wav": "WAV audio",
  "audio/wav": "WAV audio",
  "audio/vnd.wave": "WAV audio",
  "audio/x-xi": "Scream Tracker instrument",
  "audio/x-xm": "FastTracker II audio",
  "audio/x-tta": "TrueAudio audio",
  "audio/tta": "TrueAudio audio",
  "image/bmp": "Windows BMP image",
  "image/x-bmp": "Windows BMP image",
  "image/x-MS-bmp": "Windows BMP image",
  "image/vnd.wap.wbmp": "WBMP image",
  "image/cgm": "CGM image",
  "image/g3fax": "CCITT G3 fax image",
  "image/fax-g3": "CCITT G3 fax image",
  "image/gif": "GIF image",
  "image/heif": "HEIF image",
  "image/heic": "HEIF image",
  "image/heic-sequence": "HEIF image",
  "image/heif-sequence": "HEIF image",
  "image/ief": "IEF image",
  "image/jpeg": "JPEG image",
  "image/pjpeg": "JPEG image",
  "video/x-mjpeg": "MJPEG video stream",
  "image/x-jp2-codestream": "JPEG-2000 codestream",
  "image/jp2": "JPEG-2000 JP2 image",
  "image/jpeg2000": "JPEG-2000 JP2 image",
  "image/jpeg2000-image": "JPEG-2000 JP2 image",
  "image/x-jpeg2000-image": "JPEG-2000 JP2 image",
  "image/jpx": "JPEG-2000 JPX image",
  "image/jpm": "JPEG-2000 JPM image",
  "video/mj2": "JPEG-2000 MJ2 video",
  "image/jxl": "JPEG XL image",
  "image/openraster": "OpenRaster image",
  "image/x-dds": "DirectDraw surface",
  "image/x-exr": "EXR image",
  "image/x-pict": "Macintosh Quickdraw/PICT drawing",
  "application/x-ufraw": "UFRaw ID image",
  "image/x-adobe-dng": "Adobe DNG negative",
  "image/x-canon-crw": "Canon CRW raw image",
  "image/x-canon-cr2": "Canon CR2 raw image",
  "image/x-canon-cr3": "Canon CR3 raw image",
  "image/x-fuji-raf": "Fuji RAF raw image",
  "image/x-kodak-dcr": "Kodak DCR raw image",
  "image/x-kodak-k25": "Kodak K25 raw image",
  "image/x-kodak-kdc": "Kodak KDC raw image",
  "image/x-minolta-mrw": "Minolta MRW raw image",
  "image/x-nikon-nef": "Nikon NEF raw image",
  "image/x-nikon-nrw": "Nikon NRW raw image",
  "image/x-olympus-orf": "Olympus ORF raw image",
  "image/x-panasonic-rw": "Panasonic raw image",
  "image/x-panasonic-raw": "Panasonic raw image",
  "image/x-panasonic-rw2": "Panasonic raw image",
  "image/x-panasonic-raw2": "Panasonic raw image",
  "image/x-pentax-pef": "Pentax PEF raw image",
  "image/x-sigma-x3f": "Sigma X3F raw image",
  "image/x-sony-srf": "Sony SRF raw image",
  "image/x-sony-sr2": "Sony SR2 raw image",
  "image/x-sony-arw": "Sony ARW raw image",
  "image/png": "PNG image",
  "image/rle": "RLE bitmap image",
  "image/svg+xml": "SVG image",
  "image/svg+xml-compressed": "compressed SVG image",
  "image/tiff": "TIFF image",
  "image/vnd.dwg": "AutoCAD image",
  "image/vnd.dxf": "DXF vector image",
  "image/vnd.ms-modi": "MDI image",
  "image/webp": "WebP image",
  "image/x-3ds": "3D Studio image",
  "image/x-applix-graphics": "Applix Graphics image",
  "image/x-bzeps": "EPS image (bzip-compressed)",
  "image/x-cmu-raster": "CMU raster image",
  "image/x-compressed-xcf": "compressed GIMP image",
  "application/dicom": "DICOM image",
  "application/x-docbook+xml": "DocBook document",
  "application/docbook+xml": "DocBook document",
  "application/vnd.oasis.docbook+xml": "DocBook document",
  "image/vnd.djvu": "DjVu image",
  "image/x-djvu": "DjVu image",
  "image/x.djvu": "DjVu image",
  "image/vnd.djvu+multipage": "DjVu document",
  "image/x-eps": "EPS image",
  "application/fits": "FITS document",
  "image/x-fits": "FITS document",
  "image/fits": "FITS document",
  "image/x-gzeps": "EPS image (gzip-compressed)",
  "image/vnd.microsoft.icon": "Windows icon",
  "application/ico": "Windows icon",
  "image/ico": "Windows icon",
  "image/icon": "Windows icon",
  "image/x-ico": "Windows icon",
  "image/x-icon": "Windows icon",
  "text/ico": "Windows icon",
  "image/x-icns": "MacOS X icon",
  "image/x-ilbm": "ILBM image",
  "image/x-iff": "ILBM image",
  "image/x-jng": "JNG image",
  "image/x-lwo": "LightWave object",
  "image/x-lws": "LightWave scene",
  "image/x-macpaint": "MacPaint Bitmap image",
  "image/x-msod": "Office drawing",
  "image/vnd.zbrush.pcx": "PCX image",
  "image/x-pcx": "PCX image",
  "image/x-photo-cd": "PCD image",
  "image/x-portable-anymap": "PNM image",
  "image/x-portable-bitmap": "PBM image",
  "image/x-portable-graymap": "PGM image",
  "image/x-portable-pixmap": "PPM image",
  "image/vnd.adobe.photoshop": "Photoshop image",
  "image/psd": "Photoshop image",
  "image/x-psd": "Photoshop image",
  "image/photoshop": "Photoshop image",
  "image/x-photoshop": "Photoshop image",
  "application/photoshop": "Photoshop image",
  "application/x-photoshop": "Photoshop image",
  "image/x-rgb": "RGB image",
  "image/x-sgi": "SGI image",
  "image/x-sun-raster": "Sun raster image",
  "image/x-tga": "TGA image",
  "application/tga": "TGA image",
  "application/x-targa": "TGA image",
  "application/x-tga": "TGA image",
  "image/targa": "TGA image",
  "image/tga": "TGA image",
  "image/x-icb": "TGA image",
  "image/x-targa": "TGA image",
  "image/x-win-bitmap": "Windows cursor",
  "application/x-navi-animation": "Windows animated cursor",
  "image/emf": "EMF image",
  "image/x-emf": "EMF image",
  "application/x-emf": "EMF image",
  "application/emf": "EMF image",
  "image/wmf": "WMF image",
  "image/x-wmf": "WMF image",
  "image/x-win-metafile": "WMF image",
  "application/x-wmf": "WMF image",
  "application/wmf": "WMF image",
  "application/x-msmetafile": "WMF image",
  "image/x-xbitmap": "XBM image",
  "image/x-xcf": "GIMP image",
  "image/x-gimp-gbr": "GIMP brush",
  "image/x-gimp-gih": "GIMP brush pipe",
  "image/x-gimp-pat": "GIMP pattern",
  "image/x-xfig": "XFig image",
  "image/x-xpixmap": "XPM image",
  "image/x-xpm": "XPM image",
  "image/x-xwindowdump": "X window image",
  "message/rfc822": "email message",
  "model/iges": "IGES document",
  "model/gltf-binary": "glTF model",
  "model/gltf+json": "glTF model",
  "model/vrml": "VRML document",
  "model/obj": "OBJ 3D model",
  "model/mtl": "OBJ 3D model material library",
  "text/calendar": "VCS/ICS calendar",
  "text/x-vcalendar": "VCS/ICS calendar",
  "application/ics": "VCS/ICS calendar",
  "text/css": "CSS stylesheet",
  "text/vcard": "electronic business card",
  "text/directory": "electronic business card",
  "text/x-vcard": "electronic business card",
  "text/turtle": "Turtle document",
  "text/x-txt2tags": "txt2tags document",
  "text/x-verilog": "Verilog source code",
  "text/x-svhdr": "SystemVerilog header",
  "text/x-svsrc": "SystemVerilog source code",
  "text/x-vhdl": "VHDL source code",
  "text/plain": "plain text document",
  "application/rdf+xml": "RDF file",
  "text/rdf": "RDF file",
  "text/x-rst": "reStructuredText document",
  "application/owl+xml": "OWL XML file",
  "text/richtext": "rich text document",
  "application/rss+xml": "RSS summary",
  "text/rss": "RSS summary",
  "application/atom+xml": "Atom syndication feed",
  "text/x-opml+xml": "OPML syndication feed",
  "text/x-opml": "OPML syndication feed",
  "text/sgml": "SGML document",
  "text/spreadsheet": "spreadsheet interchange document",
  "text/tab-separated-values": "TSV document",
  "text/vnd.graphviz": "Graphviz DOT graph",
  "text/vnd.sun.j2me.app-descriptor": "JAD document",
  "text/vnd.wap.wml": "WML document",
  "text/vnd.wap.wmlscript": "WMLScript program",
  "text/vnd.senx.warpscript": "WarpScript source code",
  "application/x-ace": "ACE archive",
  "text/x-adasrc": "Ada source code",
  "text/x-bibtex": "BibTeX document",
  "text/x-c++hdr": "C++ header",
  "text/x-c++src": "C++ source code",
  "text/x-chdr": "C header",
  "text/x-cmake": "CMake source code",
  "text/x-common-lisp": "Common Lisp source code",
  "text/csv": "CSV document",
  "text/x-comma-separated-values": "CSV document",
  "text/x-csv": "CSV document",
  "text/csv-schema": "CSV Schema document",
  "text/x-csrc": "C source code",
  "text/x-c": "C source code",
  "text/x-csharp": "C# source code",
  "text/x-vala": "Vala source code",
  "text/x-ooc": "OOC source code",
  "text/x-dcl": "DCL script",
  "text/x-dsl": "DSSSL document",
  "text/x-dsrc": "D source code",
  "application/xml-dtd": "DTD file",
  "text/x-dtd": "DTD file",
  "text/x-eiffel": "Eiffel source code",
  "text/x-emacs-lisp": "Emacs Lisp source code",
  "text/x-elixir": "Elixir source code",
  "text/x-erlang": "Erlang source code",
  "text/x-fortran": "Fortran source code",
  "text/x-genie": "Genie source code",
  "text/x-gettext-translation": "translation file",
  "text/x-po": "translation file",
  "application/x-gettext": "translation file",
  "text/x-gettext-translation-template": "translation template",
  "text/x-pot": "translation template",
  "text/x-gherkin": "Gherkin document",
  "text/html": "HTML document",
  "text/cache-manifest": "Web application cache file",
  "text/x-google-video-pointer": "Google Video Pointer shortcut",
  "text/google-video-pointer": "Google Video Pointer shortcut",
  "text/x-haskell": "Haskell source code",
  "text/x-idl": "IDL document",
  "text/x-java": "Java source code",
  "text/x-ldif": "LDIF address book",
  "text/x-lilypond": "Lilypond music sheet",
  "text/x-literate-haskell": "LHS source code",
  "text/x-log": "application log",
  "text/x-makefile": "Makefile build file",
  "text/markdown": "Markdown document",
  "text/x-markdown": "Markdown document",
  "text/x-moc": "Qt MOC file",
  "text/x-ms-regedit": "Windows Registry extract",
  "text/x-mof": "MOF file",
  "text/x-mup": "Mup musical composition document",
  "text/x-objcsrc": "Objective-C source code",
  "text/x-objc++src": "Objective-C++ source code",
  "text/x-ocaml": "OCaml source code",
  "text/x-opencl-src": "OpenCL source code",
  "text/x-matlab": "MATLAB file",
  "text/x-octave": "MATLAB file",
  "text/x-modelica": "Modelica model",
  "text/x-pascal": "Pascal source code",
  "text/x-patch": "differences between files",
  "text/x-diff": "differences between files",
  "text/x-dart": "Dart source code",
  "text/x-go": "Go source code",
  "text/x-python3": "Python 3 script",
  "text/x-python": "Python script",
  "text/x-sagemath": "SageMath script",
  "text/x-lua": "Lua script",
  "text/x-nfo": "NFO document",
  "text/x-rpm-spec": "RPM spec file",
  "text/x-sass": "Sass CSS pre-processor file",
  "text/x-scala": "Scala source code",
  "text/x-scheme": "Scheme source code",
  "text/x-scss": "SCSS pre-processor file",
  "text/x-setext": "Setext document",
  "application/sql": "SQL code",
  "text/x-sql": "SQL code",
  "text/tcl": "Tcl script",
  "text/x-tcl": "Tcl script",
  "text/x-tex": "TeX document",
  "application/x-tex": "TeX document",
  "text/x-texinfo": "TeXInfo document",
  "text/x-troff-me": "Troff ME input document",
  "text/x-troff-mm": "Troff MM input document",
  "text/x-troff-ms": "Troff MS input document",
  "text/x-twig": "Twig template",
  "text/x-uil": "X-Motif UIL table",
  "text/x-uuencode": "uuencoded file",
  "zz-application/zz-winassoc-uu": "uuencoded file",
  "text/vbscript": "VBScript program",
  "text/vbs": "VBScript program",
  "text/x-xmi": "XMI file",
  "text/x-xslfo": "XSL FO file",
  "text/x-iptables": "iptables configuration file",
  "text/x-dbus-service": "D-Bus service file",
  "text/x-systemd-unit": "systemd unit file",
  "application/xslt+xml": "XSLT stylesheet",
  "application/xml": "XML document",
  "text/xml": "XML document",
  "application/xml-external-parsed-entity": "XML entities document",
  "text/xml-external-parsed-entity": "XML entities document",
  "video/dv": "DV video",
  "video/mp2t": "MPEG-2 transport stream",
  "video/mpeg": "MPEG video",
  "video/x-mpeg": "MPEG video",
  "video/mpeg-system": "MPEG video",
  "video/x-mpeg-system": "MPEG video",
  "video/x-mpeg2": "MPEG video",
  "video/vnd.mpegurl": "Video playlist",
  "video/x-mpegurl": "Video playlist",
  "video/quicktime": "QuickTime video",
  "image/x-quicktime": "QuickTime image",
  "image/ktx": "Khronos texture image",
  "image/ktx2": "Khronos texture image",
  "image/astc": "ASTC texture",
  "video/vnd.vivo": "Vivo video",
  "video/vivo": "Vivo video",
  "video/x-flic": "FLIC animation",
  "video/fli": "FLIC animation",
  "video/x-fli": "FLIC animation",
  "application/x-hwp": "Haansoft Hangul document",
  "application/vnd.haansoft-hwp": "Haansoft Hangul document",
  "application/x-hwt": "Haansoft Hangul document template",
  "application/vnd.haansoft-hwt": "Haansoft Hangul document template",
  "video/x-mng": "MNG animation",
  "application/vnd.ms-asf": "ASF video",
  "video/x-ms-wm": "ASF video",
  "video/x-ms-asf": "ASF video",
  "video/x-ms-asf-plugin": "ASF video",
  "application/x-netshow-channel": "Windows Media Station file",
  "video/x-ms-wmv": "Windows Media video",
  "video/x-msvideo": "AVI video",
  "video/x-avi": "AVI video",
  "video/avi": "AVI video",
  "video/divx": "AVI video",
  "video/msvideo": "AVI video",
  "video/vnd.divx": "AVI video",
  "video/x-nsv": "NullSoft video",
  "application/sdp": "SDP multicast stream file",
  "application/x-sdp": "SDP multicast stream file",
  "application/vnd.sdp": "SDP multicast stream file",
  "video/x-sgi-movie": "SGI video",
  "application/vnd.emusic-emusic_package": "eMusic download package",
  "application/vnd.google-earth.kml+xml": "KML geographic data",
  "application/vnd.google-earth.kmz": "KML geographic compressed data",
  "application/geo+json": "GeoJSON geospatial data",
  "application/vnd.geo+json": "GeoJSON geospatial data",
  "application/gpx+xml": "GPX geographic data",
  "application/gpx": "GPX geographic data",
  "application/x-gpx+xml": "GPX geographic data",
  "application/x-gpx": "GPX geographic data",
  "application/x-ica": "Citrix ICA settings file",
  "application/vnd.mozilla.xul+xml": "XUL interface document",
  "application/x-xpinstall": "XPInstall installer module",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "Word 2007 document",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.template": "Word 2007 document template",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "PowerPoint 2007 presentation",
  "application/vnd.openxmlformats-officedocument.presentationml.slide": "PowerPoint 2007 slide",
  "application/vnd.openxmlformats-officedocument.presentationml.slideshow": "PowerPoint 2007 show",
  "application/vnd.openxmlformats-officedocument.presentationml.template": "PowerPoint 2007 presentation template",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "Excel 2007 spreadsheet",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.template": "Excel 2007 spreadsheet template",
  "application/x-t602": "T602 document",
  "application/x-cisco-vpn-settings": "Cisco VPN settings",
  "application/vnd.iccprofile": "ICC profile",
  "application/x-it87": "IT 8.7 color calibration file",
  "application/x-ccmx": "CCMX color correction file",
  "application/winhlp": "WinHelp help file",
  "zz-application/zz-winassoc-hlp": "WinHelp help file",
  "application/x-bsdiff": "binary differences between files",
  "application/trig": "TriG RDF document",
  "application/x-trig": "TriG RDF document",
  "application/vnd.apple.keynote": "Apple Keynote 5 presentation",
  "application/x-iwork-keynote-sffkey": "Apple Keynote 5 presentation",
  "application/vnd.apple.numbers": "Apple Numbers spreadsheet",
  "application/x-iwork-numbers-sffnumbers": "Apple Numbers spreadsheet",
  "application/vnd.apple.pages": "Apple Pages document",
  "application/x-iwork-pages-sffpages": "Apple Pages document",
  "application/vnd.apple.pkpass": "Apple Wallet pass",
  "application/x-pagemaker": "Adobe PageMaker document",
  "application/x-doom-wad": "Doom WAD file",
  "application/x-amiga-disk-format": "Amiga disk image",
  "application/vnd.flatpak": "Flatpak application bundle",
  "application/vnd.xdgapp": "Flatpak application bundle",
  "application/vnd.flatpak.repo": "Flatpak repository description",
  "application/vnd.flatpak.ref": "Flatpak repository reference",
  "application/vnd.squashfs": "Squashfs filesystem image",
  "application/vnd.appimage": "AppImage application bundle",
  "application/vnd.snap": "Snap package",
  "model/3mf": "3MF document",
  "application/vnd.ms-3mfdocument": "3MF document",
  "model/stl": "STL 3D model",
  "model/x.stl-ascii": "STL 3D model",
  "model/x.stl-binary": "STL 3D model",
  "text/x.gcode": "G-code file",
  "text/x-gcode-gx": "G-code Extended file",
  "application/x-fds-disk": "Nintendo FDS disk image",
  "application/ovf": "OVF disk image",
  "application/x-virtualbox-ova": "OVF disk image",
  "application/x-qed-disk": "QEMU QED disk image",
  "application/x-qemu-disk": "QEMU QCOW disk image",
  "application/x-vhd-disk": "VHD disk image",
  "application/x-virtualbox-vhd": "VHD disk image",
  "application/x-vhdx-disk": "VHDX disk image",
  "application/x-virtualbox-vhdx": "VHDX disk image",
  "application/x-vmdk-disk": "VMDK disk image",
  "application/x-virtualbox-vmdk": "VMDK disk image",
  "application/x-vdi-disk": "VDI disk image",
  "application/x-virtualbox-vdi": "VDI disk image",
  "application/x-appleworks-document": "AppleWorks document",
  "application/x-bps-patch": "BPS patch",
  "application/x-ips-patch": "IPS patch",
  "application/x-pyspread-spreadsheet": "Pyspread spreadsheet",
  "application/x-pyspread-bz-spreadsheet": "Pyspread spreadsheet (bzip-compressed)",
  "text/x-kotlin": "Kotlin source code",
  "image/avif": "AVIF image",
  "image/avif-sequence": "AVIF image",
  "video/vnd.radgamettools.bink": "Bink Video",
  "video/vnd.radgamettools.smacker": "Smacker Video",
  "text/org": "Org-mode file",
  "application/x-openzim": "OpenZIM file",
  "application/sparql-query": "SPARQL query",
  "application/sparql-results+xml": "SPARQL query results"
}
